## Load Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## load Datase

In [2]:
df = pd.read_csv("demandpulse_ai.csv")

## First Look

In [3]:
df

,date,day_of_week,day_of_month,week_of_year,month,quarter,year,product_id,product_name,category,...,is_weekend,is_holiday,holiday_name,season,special_event,inventory_level,lead_time_days,stockout_flag,supplier_id,minimum_order_quantity
0,2025-07-01,Tuesday,1,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,302,2,0,SUP005,50
1,2025-07-02,Wednesday,2,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,187,2,0,SUP008,100
2,2025-07-03,Thursday,3,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,140,7,0,SUP004,25
3,2025-07-04,Friday,4,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,127,3,0,SUP009,10
4,2025-07-05,Saturday,5,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,1,0,NaN,Monsoon,NaN,323,7,0,SUP013,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2025-10-04,Saturday,4,40,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,1,0,NaN,Autumn,NaN,502,4,0,SUP008,50
999996,2025-10-05,Sunday,5,40,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,1,0,NaN,Autumn,NaN,444,7,0,SUP003,75
999997,2025-10-06,Monday,6,41,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,0,0,NaN,Autumn,NaN,182,3,0,SUP004,100
999998,2025-10-07,Tuesday,7,41,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,0,0,NaN,Autumn,NaN,248,1,0,SUP009,200
999999,2025-10-08,Wednesday,8,41,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,0,0,NaN,Autumn,NaN,333,1,0,SUP003,10

In [4]:
df.head()

,date,day_of_week,day_of_month,week_of_year,month,quarter,year,product_id,product_name,category,...,is_weekend,is_holiday,holiday_name,season,special_event,inventory_level,lead_time_days,stockout_flag,supplier_id,minimum_order_quantity
0,2025-07-01,Tuesday,1,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,302,2,0,SUP005,50
1,2025-07-02,Wednesday,2,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,187,2,0,SUP008,100
2,2025-07-03,Thursday,3,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,140,7,0,SUP004,25
3,2025-07-04,Friday,4,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,0,0,NaN,Monsoon,NaN,127,3,0,SUP009,10
4,2025-07-05,Saturday,5,27,7,3,2025,P00001,Brand_C Detergent Product 001,Household,...,1,0,NaN,Monsoon,NaN,323,7,0,SUP013,25

In [5]:
df.tail()

,date,day_of_week,day_of_month,week_of_year,month,quarter,year,product_id,product_name,category,...,is_weekend,is_holiday,holiday_name,season,special_event,inventory_level,lead_time_days,stockout_flag,supplier_id,minimum_order_quantity
999995,2025-10-04,Saturday,4,40,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,1,0,NaN,Autumn,NaN,502,4,0,SUP008,50
999996,2025-10-05,Sunday,5,40,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,1,0,NaN,Autumn,NaN,444,7,0,SUP003,75
999997,2025-10-06,Monday,6,41,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,0,0,NaN,Autumn,NaN,182,3,0,SUP004,100
999998,2025-10-07,Tuesday,7,41,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,0,0,NaN,Autumn,NaN,248,1,0,SUP009,200
999999,2025-10-08,Wednesday,8,41,10,4,2025,P00200,Brand_E Tea Product 200,Beverages,...,0,0,NaN,Autumn,NaN,333,1,0,SUP003,10

In [6]:
df.shape

(1000000, 35)

In [7]:
df.columns

Index(['date', 'day_of_week', 'day_of_month', 'week_of_year', 'month',
       'quarter', 'year', 'product_id', 'product_name', 'category',
       'subcategory', 'brand', 'unit_of_measure', 'store_id', 'store_type',
       'store_location', 'city', 'region', 'quantity_sold', 'sales_amount',
       'number_of_transactions', 'average_selling_price', 'promotion_type',
       'discount_percentage', 'is_promoted', 'is_weekend', 'is_holiday',
       'holiday_name', 'season', 'special_event', 'inventory_level',
       'lead_time_days', 'stockout_flag', 'supplier_id',
       'minimum_order_quantity'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 35 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   date                    1000000 non-null  object
 1   day_of_week             1000000 non-null  object
 2   day_of_month            1000000 non-null  int64
 3   week_of_year            1000000 non-null  int64
 4   month                   1000000 non-null  int64
 5   quarter                 1000000 non-null  int64
 6   year                    1000000 non-null  int64
 7   product_id              1000000 non-null  object
 8   product_name            1000000 non-null  object
 9   category                1000000 non-null  object
 10  subcategory             1000000 non-null  object
 11  brand                   1000000 non-null  object
 12  unit_of_measure         1000000 non-null  object
 13  store_id                1000000 non-null  object
 14  store_type              1000000 non-null  object
 15  store_location          1000000 non-null  object
 16  city                    1000000 non-null  object
 17  region                  1000000 non-null  object
 18  quantity_sold           1000000 non-null  int64
 19  sales_amount            1000000 non-null  float64
 20  number_of_transactions  1000000 non-null  int64
 21  average_selling_price   1000000 non-null  float64
 22  promotion_type          1000000 non-null  object
 23  discount_percentage     1000000 non-null  float64
 24  is_promoted             1000000 non-null  int64
 25  is_weekend              1000000 non-null  int64
 26  is_holiday              1000000 non-null  int64
 27  holiday_name            30000 non-null    object
 28  season                  1000000 non-null  object
 29  special_event           30000 non-null    object
 30  inventory_level         1000000 non-null  int64
 31  lead_time_days          1000000 non-null  int64
 32  stockout_flag           1000000 non-null  int64
 33  supplier_id             1000000 non-null  object
 34  minimum_order_quantity  1000000 non-null  int64
dtypes: float64(3), int64(14), object(18)
memory usage: 267.0+ MB

In [9]:
df.isnull().sum()

date                           0
day_of_week                    0
day_of_month                   0
week_of_year                   0
month                          0
quarter                        0
year                           0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
unit_of_measure                0
store_id                       0
store_type                     0
store_location                 0
city                           0
region                         0
quantity_sold                  0
sales_amount                   0
number_of_transactions         0
average_selling_price          0
promotion_type                 0
discount_percentage            0
is_promoted                    0
is_weekend                     0
is_holiday                     0
holiday_name              970000
season                         0
special_event             970000
inventory_level                0
lead_time_days                 0
stockout_flag                  0
supplier_id                    0
minimum_order_quantity         0
dtype: int64

## Random Sample

In [10]:
df.sample(5, random_state=42)

,date,day_of_week,day_of_month,week_of_year,month,quarter,year,product_id,product_name,category,...,is_weekend,is_holiday,holiday_name,season,special_event,inventory_level,lead_time_days,stockout_flag,supplier_id,minimum_order_quantity
987231,2025-08-01,Friday,1,31,8,3,2025,P00198,Brand_A Rice Product 198,Grocery,...,0,0,NaN,Monsoon,NaN,75,7,0,SUP019,25
79954,2025-08-24,Sunday,24,34,8,3,2025,P00016,Brand_E Pulses Product 016,Grocery,...,1,0,NaN,Monsoon,NaN,97,5,0,SUP006,75
567130,2025-07-31,Thursday,31,31,7,3,2025,P00114,Brand_A Flour Product 114,Grocery,...,0,0,NaN,Monsoon,NaN,62,10,0,SUP010,200
500891,2025-09-30,Tuesday,30,40,9,3,2025,P00101,Brand_A Skincare Product 101,Personal Care,...,0,0,NaN,Monsoon,NaN,215,3,0,SUP014,100
55399,2025-10-08,Wednesday,8,41,10,4,2025,P00012,Brand_D Cleaning Product 012,Household,...,0,0,NaN,Autumn,NaN,402,4,0,SUP020,10

In [11]:
df.columns.tolist()

['date',
 'day_of_week',
 'day_of_month',
 'week_of_year',
 'month',
 'quarter',
 'year',
 'product_id',
 'product_name',
 'category',
 'subcategory',
 'brand',
 'unit_of_measure',
 'store_id',
 'store_type',
 'store_location',
 'city',
 'region',
 'quantity_sold',
 'sales_amount',
 'number_of_transactions',
 'average_selling_price',
 'promotion_type',
 'discount_percentage',
 'is_promoted',
 'is_weekend',
 'is_holiday',
 'holiday_name',
 'season',
 'special_event',
 'inventory_level',
 'lead_time_days',
 'stockout_flag',
 'supplier_id',
 'minimum_order_quantity']

In [12]:
df.dtypes

date                       object
day_of_week                object
day_of_month                int64
week_of_year                int64
month                       int64
quarter                     int64
year                        int64
product_id                 object
product_name               object
category                   object
subcategory                object
brand                      object
unit_of_measure            object
store_id                   object
store_type                 object
store_location             object
city                       object
region                     object
quantity_sold               int64
sales_amount              float64
number_of_transactions      int64
average_selling_price     float64
promotion_type             object
discount_percentage       float64
is_promoted                 int64
is_weekend                  int64
is_holiday                  int64
holiday_name               object
season                     object
special_event              object
inventory_level             int64
lead_time_days              int64
stockout_flag               int64
supplier_id                object
minimum_order_quantity      int64
dtype: object

In [13]:
df["date"] = pd.to_datetime(df["date"])

In [14]:
print(df["date"].dtype)

datetime64[ns]

In [15]:
df.duplicated().sum()

0

In [16]:
print("Products:", df["product_id"].nunique())
print("Stores:", df["store_id"].nunique())
print("Suppliers:", df["supplier_id"].nunique())

Products: 200
Stores: 50
Suppliers: 20

In [17]:
numeric_cols = df.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

print(numeric_cols)

['day_of_month', 'week_of_year', 'month', 'quarter', 'year', 'quantity_sold', 'sales_amount', 'number_of_transactions', 'average_selling_price', 'discount_percentage', 'is_promoted', 'is_weekend', 'is_holiday', 'inventory_level', 'lead_time_days', 'stockout_flag', 'minimum_order_quantity']

In [18]:
df[numeric_cols].describe().T

,count,mean,std,min,25%,50%,75%,max
day_of_month,1000000.0,14.930000,9.055671,1.00,7.000,14.500,23.0000,31.00
week_of_year,1000000.0,33.790000,4.135930,27.00,30.000,34.000,37.0000,41.00
month,1000000.0,8.150000,0.952628,7.00,7.000,8.000,9.0000,10.00
quarter,1000000.0,3.080000,0.271293,3.00,3.000,3.000,3.0000,4.00
year,1000000.0,2025.000000,0.000000,2025.00,2025.000,2025.000,2025.0000,2025.00
quantity_sold,1000000.0,119.628193,72.044503,2.00,64.000,105.000,160.0000,1000.00
sales_amount,1000000.0,72806.501130,68051.389736,205.52,20659.005,51818.035,105223.6825,724364.50
number_of_transactions,1000000.0,83.756919,51.863803,1.00,44.000,73.000,112.0000,808.00
average_selling_price,1000000.0,587.601977,358.250188,15.09,272.020,559.895,912.9800,1231.93
discount_percentage,1000000.0,2.607132,6.641315,0.00,0.000,0.000,0.0000,40.00
is_promoted,1000000.0,0.153883,0.360837,0.00,0.000,0.000,0.0000,1.00
is_weekend,1000000.0,0.280000,0.448999,0.00,0.000,0.000,1.0000,1.00
is_holiday,1000000.0,0.030000,0.170587,0.00,0.000,0.000,0.0000,1.00
inventory_level,1000000.0,317.970826,211.780273,2.00,159.000,272.000,431.0000,2145.00
lead_time_days,1000000.0,4.061127,2.140691,1.00,3.000,4.000,5.0000,10.00
stockout_flag,1000000.0,0.055332,0.228627,0.00,0.000,0.000,0.0000,1.00
minimum_order_quantity,1000000.0,65.255870,53.422841,10.00,25.000,50.000,100.0000,200.00

In [19]:
df["quantity_sold"].describe()

count    1000000.000000
mean         119.628193
std           72.044503
min            2.000000
25%           64.000000
50%          105.000000
75%          160.000000
max         1000.000000
Name: quantity_sold, dtype: float64

In [20]:
df["quantity_sold"].value_counts().head(20)

quantity_sold
61    6828
62    6816
54    6814
59    6749
53    6728
58    6692
64    6686
63    6684
52    6676
60    6675
69    6674
51    6659
65    6656
68    6652
50    6648
67    6627
71    6617
57    6610
66    6601
55    6588
Name: count, dtype: int64

In [21]:
print("Mean demand  :", df["quantity_sold"].mean())
print("Median demand:", df["quantity_sold"].median())
print("Std demand   :", df["quantity_sold"].std())
print("Min demand   :", df["quantity_sold"].min())
print("Max demand   :", df["quantity_sold"].max())

Mean demand  : 119.628193
Median demand: 105.0
Std demand   : 72.04450305863554
Min demand   : 2
Max demand   : 1000

In [22]:
zero_demand = (
    df["quantity_sold"] == 0
).sum()

print("Zero-demand rows:", zero_demand)

print(
    "Zero-demand %:",
    round(zero_demand / len(df) * 100, 2)
)

Zero-demand rows: 0
Zero-demand %: 0.0

In [23]:
print(
    "Unique products:",
    df["product_id"].nunique()
)

Unique products: 200

In [24]:
category_sales = (
    df.groupby("category")["quantity_sold"]
    .sum()
    .sort_values(ascending=False)
)

category_sales

category
Snacks           27362332
Grocery          26243778
Household        25120394
Beverages        21580641
Personal Care    19321048
Name: quantity_sold, dtype: int64

In [25]:
category_demand = (
    df.groupby("category")["quantity_sold"]
    .mean()
    .sort_values(ascending=False)
)

category_demand

category
Household        132.212600
Personal Care    124.651923
Snacks           121.610364
Grocery          114.103383
Beverages        107.903205
Name: quantity_sold, dtype: float64

In [26]:
top_products = (
    df.groupby(["product_id", "product_name"])["quantity_sold"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

product_id  product_name
P00093      Brand_D Flour Product 093       1079924
P00014      Brand_E Chips Product 014       1077725
P00139      Brand_B Cleaning Product 139    1076022
P00177      Brand_B Tea Product 177         1067647
P00043      Brand_C Cleaning Product 043    1066652
P00005      Brand_C Pulses Product 005      1064499
P00151      Brand_A Soap Product 151        1060400
P00089      Brand_E Namkeen Product 089     1059400
P00145      Brand_E Water Product 145       1057411
P00102      Brand_C Rice Product 102        1051483
Name: quantity_sold, dtype: int64

In [27]:
store_demand = (
    df.groupby("store_id")["quantity_sold"]
    .sum()
    .sort_values(ascending=False)
)

store_demand.head(10)

store_id
S0046    3536122
S0042    3534841
S0037    3531958
S0024    3530244
S0026    2946368
S0039    2941819
S0029    2941807
S0027    2940574
S0017    2939295
S0045    2932527
Name: quantity_sold, dtype: int64

In [28]:
store_avg_demand = (
    df.groupby("store_id")["quantity_sold"]
    .mean()
    .sort_values(ascending=False)
)

store_avg_demand.head(10)

store_id
S0046    176.80610
S0042    176.74205
S0037    176.59790
S0024    176.51220
S0026    147.31840
S0039    147.09095
S0029    147.09035
S0027    147.02870
S0017    146.96475
S0045    146.62635
Name: quantity_sold, dtype: float64

In [29]:
region_demand = (
    df.groupby("region")["quantity_sold"]
    .agg(["sum", "mean", "std"])
    .sort_values("sum", ascending=False)
)

region_demand

             sum        mean        std
region
North   42764056  118.789044  72.591698
West    29474006  122.808358  71.733894
South   28095717  117.065488  71.519516
East    19294414  120.590087  71.867545

In [30]:
dow_demand = (
    df.groupby("day_of_week")["quantity_sold"]
    .agg(["sum", "mean"])
)

dow_demand

                  sum        mean
day_of_week
Friday       17362168  124.015486
Monday       14571575  104.082679
Saturday     19709919  140.785136
Sunday       18581930  132.728071
Thursday     16002779  114.305564
Tuesday      16027587  106.850580
Wednesday    17372235  115.814900

In [31]:
day_order = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday"
]

dow_demand = (
    df.groupby("day_of_week")["quantity_sold"]
    .mean()
    .reindex(day_order)
)

dow_demand

day_of_week
Monday       104.082679
Tuesday      106.850580
Wednesday    115.814900
Thursday     114.305564
Friday       124.015486
Saturday     140.785136
Sunday       132.728071
Name: quantity_sold, dtype: float64

In [32]:
monthly_demand = (
    df.groupby("month")["quantity_sold"]
    .agg(["sum", "mean"])
)

monthly_demand

            sum        mean
month
7      33558821  108.254261
8      37719883  121.677042
9      37185063  123.950210
10     11164426  139.555325

In [33]:
season_demand = (
    df.groupby("season")["quantity_sold"]
    .agg(["sum", "mean"])
    .sort_values("mean", ascending=False)
)

season_demand

               sum        mean
season
Autumn    11164426  139.555325
Monsoon  108463767  117.895399

In [34]:
promotion_demand = (
    df.groupby("is_promoted")["quantity_sold"]
    .agg(["count", "mean", "sum"])
)

promotion_demand

              count        mean       sum
is_promoted
0            846117  115.032384  97330856
1            153883  144.897987  22297337

In [35]:
promotion_type_analysis = (
    df.groupby("promotion_type")["quantity_sold"]
    .agg(["count", "mean", "sum"])
    .sort_values("mean", ascending=False)
)

promotion_type_analysis

                 count        mean       sum
promotion_type
Clearance        15382  163.345924   2512587
Festival Offer   30791  149.054367   4589533
BOGO             30940  141.993794   4393288
Discount         53673  141.704227   7605691
Bundle           23097  138.383253   3196238
No Promotion    846117  115.032384  97330856

In [36]:
discount_analysis = (
    df.groupby("promotion_type")[
        ["discount_percentage", "quantity_sold"]
    ].mean()
)

discount_analysis

                discount_percentage  quantity_sold
promotion_type
BOGO                      14.988896     141.993794
Bundle                    12.966623     138.383253
Clearance                 27.455882     163.345924
Discount                  15.006292     141.704227
Festival Offer            20.009939     149.054367
No Promotion               0.000000     115.032384

In [37]:
stockout_analysis = (
    df.groupby("stockout_flag")["quantity_sold"]
    .agg(["count", "mean", "sum"])
)

stockout_analysis

                count        mean        sum
stockout_flag
0              944668  123.240511  116421367
1               55332   57.956083    3206826

In [38]:
print(
    df["stockout_flag"]
    .value_counts(normalize=True)
    .mul(100)
)

stockout_flag
0    94.4668
1     5.5332
Name: proportion, dtype: float64

In [39]:
inventory_analysis = df[
    ["inventory_level", "quantity_sold"]
].describe()

inventory_analysis

       inventory_level   quantity_sold
count   1000000.000000  1000000.000000
mean        317.970826      119.628193
std         211.780273       72.044503
min           2.000000        2.000000
25%         159.000000       64.000000
50%         272.000000      105.000000
75%         431.000000      160.000000
max        2145.000000     1000.000000

In [40]:
lead_time_analysis = (
    df.groupby("lead_time_days")["quantity_sold"]
    .agg(["count", "mean"])
)

lead_time_analysis

                 count        mean
lead_time_days
1                79686  119.574907
2               150622  119.887752
3               220049  119.866866
4               219010  119.656874
5               160467  119.334287
7               119995  119.365949
10               50171  119.328815

In [41]:
categorical_cols = df.select_dtypes(
    include="object"
).columns

for col in categorical_cols:
    print(
        f"{col:25} → {df[col].nunique()} unique values"
    )

day_of_week               → 7 unique values
product_id                → 200 unique values
product_name              → 200 unique values
category                  → 5 unique values
subcategory               → 20 unique values
brand                     → 5 unique values
unit_of_measure           → 6 unique values
store_id                  → 50 unique values
store_type                → 3 unique values
store_location            → 3 unique values
city                      → 12 unique values
region                    → 4 unique values
promotion_type            → 6 unique values
holiday_name              → 2 unique values
season                    → 2 unique values
special_event             → 2 unique values
supplier_id               → 20 unique values

In [42]:
def outlier_summary(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower) |
        (data[column] > upper)
    ]

    print(f"\nColumn: {column}")
    print(f"Q1: {Q1:.2f}")
    print(f"Q3: {Q3:.2f}")
    print(f"IQR: {IQR:.2f}")
    print(f"Lower Bound: {lower:.2f}")
    print(f"Upper Bound: {upper:.2f}")
    print(f"Outliers: {len(outliers):,}")
    print(f"Outlier %: {len(outliers)/len(data)*100:.2f}%")

In [43]:
outlier_summary(df, "quantity_sold")
outlier_summary(df, "sales_amount")
outlier_summary(df, "average_selling_price")
outlier_summary(df, "inventory_level")

Column: quantity_sold
Q1: 64.00
Q3: 160.00
IQR: 96.00
Lower Bound: -80.00
Upper Bound: 304.00
Outliers: 20,190
Outlier %: 2.02%

Column: sales_amount
Q1: 20659.01
Q3: 105223.68
IQR: 84564.68
Lower Bound: -106188.01
Upper Bound: 232070.70
Outliers: 34,163
Outlier %: 3.42%

Column: average_selling_price
Q1: 272.02
Q3: 912.98
IQR: 640.96
Lower Bound: -689.42
Upper Bound: 1874.42
Outliers: 0
Outlier %: 0.00%

Column: inventory_level
Q1: 159.00
Q3: 431.00
IQR: 272.00
Lower Bound: -249.00
Upper Bound: 839.00
Outliers: 25,140
Outlier %: 2.51%

In [44]:
correlation = df[numeric_cols].corr()

correlation["quantity_sold"].sort_values(
    ascending=False
)

quantity_sold             1.000000
number_of_transactions    0.972382
inventory_level           0.826509
sales_amount              0.690122
discount_percentage       0.162246
is_promoted               0.149583
is_weekend                0.148262
month                     0.116723
week_of_year              0.110311
is_holiday                0.099198
average_selling_price     0.097355
quarter                   0.081563
day_of_month              0.009685
minimum_order_quantity   -0.000463
lead_time_days           -0.002267
stockout_flag            -0.207175
year                           NaN
Name: quantity_sold, dtype: float64

In [45]:
quality_report = pd.DataFrame({
    "dtype": df.dtypes,
    "missing_count": df.isnull().sum(),
    "missing_percentage": (
        df.isnull().mean() * 100
    ).round(2),
    "unique_values": df.nunique()
})

quality_report

,dtype,missing_count,missing_percentage,unique_values
date,datetime64[ns],0,0.0,100
day_of_week,object,0,0.0,7
day_of_month,int64,0,0.0,31
week_of_year,int64,0,0.0,15
month,int64,0,0.0,4
quarter,int64,0,0.0,2
year,int64,0,0.0,1
product_id,object,0,0.0,200
product_name,object,0,0.0,200
category,object,0,0.0,5
subcategory,object,0,0.0,20
brand,object,0,0.0,5
unit_of_measure,object,0,0.0,6
store_id,object,0,0.0,50
store_type,object,0,0.0,3
store_location,object,0,0.0,3
city,object,0,0.0,12
region,object,0,0.0,4
quantity_sold,int64,0,0.0,636
sales_amount,float64,0,0.0,887665
number_of_transactions,int64,0,0.0,481
average_selling_price,float64,0,0.0,118328
promotion_type,object,0,0.0,6
discount_percentage,float64,0,0.0,3501
is_promoted,int64,0,0.0,2
is_weekend,int64,0,0.0,2
is_holiday,int64,0,0.0,2
holiday_name,object,970000,97.0,2
season,object,0,0.0,2
special_event,object,970000,97.0,2
inventory_level,int64,0,0.0,1645
lead_time_days,int64,0,0.0,7
stockout_flag,int64,0,0.0,2
supplier_id,object,0,0.0,20
minimum_order_quantity,int64,0,0.0,6

In [46]:
quality_report.to_csv(
    "demandpulse_data_quality_report.csv"
)

In [47]:
df["holiday_name"] = df["holiday_name"].fillna("No Holiday")
df["special_event"] = df["special_event"].fillna("No Event")

In [48]:
print(df["holiday_name"].isna().sum())
print(df["special_event"].isna().sum())

0
0

In [49]:
df["date"] = pd.to_datetime(df["date"])
print(df["date"].dtype)

datetime64[ns]

In [50]:
df = df.drop_duplicates()

In [51]:
duplicate_keys = df.duplicated(
    subset=["date", "product_id", "store_id"]
).sum()

print(
    "Duplicate product-store-date:",
    duplicate_keys
)

Duplicate product-store-date: 0

In [52]:
duplicate_keys = df.duplicated(
    subset=["date", "product_id", "store_id"]
).sum()

print(
    "Duplicate product-store-date:",
    duplicate_keys
)

Duplicate product-store-date: 0

In [53]:
print(
    "Negative sales:",
    (df["sales_amount"] < 0).sum()
)

Negative sales: 0

In [54]:
print(
    "Negative inventory:",
    (df["inventory_level"] < 0).sum()
)

Negative inventory: 0

In [55]:
zero_sales = (df["quantity_sold"] == 0).sum()

print("Zero-sales rows:", zero_sales)

Zero-sales rows: 0

In [56]:
binary_cols = [
    "is_promoted",
    "is_weekend",
    "is_holiday",
    "stockout_flag"
]

for col in binary_cols:
    print(
        col,
        sorted(df[col].unique())
    )

is_promoted [0, 1]
is_weekend [0, 1]
is_holiday [0, 1]
stockout_flag [0, 1]

In [57]:
invalid_promo = df[
    (df["is_promoted"] == 0) &
    (
        (df["promotion_type"] != "No Promotion") |
        (df["discount_percentage"] != 0)
    )
]

print(
    "Invalid promotion records:",
    len(invalid_promo)
)

Invalid promotion records: 0

In [58]:
invalid_holiday = df[
    (df["is_holiday"] == 0) &
    (df["holiday_name"] != "No Holiday")
]

print(
    "Invalid holiday records:",
    len(invalid_holiday)
)

Invalid holiday records: 0

In [59]:
invalid_holiday_2 = df[
    (df["is_holiday"] == 1) &
    (df["holiday_name"] == "No Holiday")
]

print(
    "Invalid holiday flag records:",
    len(invalid_holiday_2)
)

Invalid holiday flag records: 0

In [60]:
invalid_event = df[
    (df["special_event"] == "No Event") &
    (df["is_holiday"] == 1)
]

print(
    "Potential event inconsistencies:",
    len(invalid_event)
)

Potential event inconsistencies: 0

In [61]:
print(
    "Non-positive selling price:",
    (df["average_selling_price"] <= 0).sum()
)

Non-positive selling price: 0

In [62]:
invalid_discount = df[
    (df["discount_percentage"] < 0) |
    (df["discount_percentage"] > 100)
]

print(
    "Invalid discount records:",
    len(invalid_discount)
)

Invalid discount records: 0

In [63]:
print(
    "Invalid lead time:",
    (df["lead_time_days"] <= 0).sum()
)

Invalid lead time: 0

In [64]:
print(
    "Invalid MOQ:",
    (df["minimum_order_quantity"] <= 0).sum()
)

Invalid MOQ: 0

In [65]:
categorical_cols = df.select_dtypes(
    include="object"
).columns

for col in categorical_cols:
    df[col] = df[col].str.strip()

In [66]:
categorical_cols = df.select_dtypes(
    include="object"
).columns

for col in categorical_cols:
    df[col] = df[col].str.strip()

In [67]:
print("=" * 55)
print("      DEMANDPULSE AI — CLEANING VALIDATION")
print("=" * 55)

print("Shape:", df.shape)

print(
    "Missing values:",
    df.isnull().sum().sum()
)

print(
    "Duplicate rows:",
    df.duplicated().sum()
)

print(
    "Duplicate product-store-date:",
    df.duplicated(
        ["date", "product_id", "store_id"]
    ).sum()
)

print(
    "Negative quantity:",
    (df["quantity_sold"] < 0).sum()
)

print(
    "Negative sales:",
    (df["sales_amount"] < 0).sum()
)

print(
    "Negative inventory:",
    (df["inventory_level"] < 0).sum()
)

print(
    "Invalid discount:",
    (
        (df["discount_percentage"] < 0) |
        (df["discount_percentage"] > 100)
    ).sum()
)

print("=" * 55)

=======================================================
      DEMANDPULSE AI — CLEANING VALIDATION
=======================================================
Shape: (1000000, 35)
Missing values: 0
Duplicate rows: 0
Duplicate product-store-date: 0
Negative quantity: 0
Negative sales: 0
Negative inventory: 0
Invalid discount: 0
=======================================================

In [68]:
print("Current memory usage:")
df.info(memory_usage="deep")

Current memory usage:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 35 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   date                    1000000 non-null  datetime64[ns]
 1   day_of_week             1000000 non-null  object
 2   day_of_month            1000000 non-null  int64
 3   week_of_year            1000000 non-null  int64
 4   month                   1000000 non-null  int64
 5   quarter                 1000000 non-null  int64
 6   year                    1000000 non-null  int64
 7   product_id              1000000 non-null  object
 8   product_name            1000000 non-null  object
 9   category                1000000 non-null  object
 10  subcategory             1000000 non-null  object
 11  brand                   1000000 non-null  object
 12  unit_of_measure         1000000 non-null  object
 13  store_id                1000000 non-null  object
 14  store_type              1000000 non-null  object
 15  store_location          1000000 non-null  object
 16  city                    1000000 non-null  object
 17  region                  1000000 non-null  object
 18  quantity_sold           1000000 non-null  int64
 19  sales_amount            1000000 non-null  float64
 20  number_of_transactions  1000000 non-null  int64
 21  average_selling_price   1000000 non-null  float64
 22  promotion_type          1000000 non-null  object
 23  discount_percentage     1000000 non-null  float64
 24  is_promoted             1000000 non-null  int64
 25  is_weekend              1000000 non-null  int64
 26  is_holiday              1000000 non-null  int64
 27  holiday_name            1000000 non-null  object
 28  season                  1000000 non-null  object
 29  special_event           1000000 non-null  object
 30  inventory_level         1000000 non-null  int64
 31  lead_time_days          1000000 non-null  int64
 32  stockout_flag           1000000 non-null  int64
 33  supplier_id             1000000 non-null  object
 34  minimum_order_quantity  1000000 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(14), object(17)
memory usage: 1.0 GB

In [69]:
memory_before = df.memory_usage(deep=True).sum() / 1024**2

print(f"Memory Before Optimization: {memory_before:.2f} MB")

Memory Before Optimization: 1068.72 MB

In [70]:
df.dtypes

date                      datetime64[ns]
day_of_week                       object
day_of_month                       int64
week_of_year                       int64
month                              int64
quarter                            int64
year                               int64
product_id                        object
product_name                      object
category                          object
subcategory                       object
brand                             object
unit_of_measure                   object
store_id                          object
store_type                        object
store_location                    object
city                              object
region                            object
quantity_sold                      int64
sales_amount                     float64
number_of_transactions             int64
average_selling_price            float64
promotion_type                    object
discount_percentage              float64
is_promoted                        int64
is_weekend                         int64
is_holiday                         int64
holiday_name                      object
season                            object
special_event                     object
inventory_level                    int64
lead_time_days                     int64
stockout_flag                      int64
supplier_id                       object
minimum_order_quantity             int64
dtype: object

In [71]:
categorical_cols = [
    "day_of_week",
    "product_id",
    "product_name",
    "category",
    "subcategory",
    "brand",
    "unit_of_measure",
    "store_id",
    "store_type",
    "store_location",
    "city",
    "region",
    "promotion_type",
    "holiday_name",
    "season",
    "special_event",
    "supplier_id"
]

print(categorical_cols)

['day_of_week', 'product_id', 'product_name', 'category', 'subcategory', 'brand', 'unit_of_measure', 'store_id', 'store_type', 'store_location', 'city', 'region', 'promotion_type', 'holiday_name', 'season', 'special_event', 'supplier_id']

In [72]:
for col in categorical_cols:
    df[col] = df[col].astype("category")

In [73]:
df.dtypes

date                      datetime64[ns]
day_of_week                     category
day_of_month                       int64
week_of_year                       int64
month                              int64
quarter                            int64
year                               int64
product_id                      category
product_name                    category
category                        category
subcategory                     category
brand                           category
unit_of_measure                 category
store_id                        category
store_type                      category
store_location                  category
city                            category
region                          category
quantity_sold                      int64
sales_amount                     float64
number_of_transactions             int64
average_selling_price            float64
promotion_type                  category
discount_percentage              float64
is_promoted                        int64
is_weekend                         int64
is_holiday                         int64
holiday_name                    category
season                          category
special_event                   category
inventory_level                    int64
lead_time_days                     int64
stockout_flag                      int64
supplier_id                     category
minimum_order_quantity             int64
dtype: object

In [74]:
integer_cols = [
    "day_of_month",
    "week_of_year",
    "month",
    "quarter",
    "year",
    "quantity_sold",
    "number_of_transactions",
    "is_promoted",
    "is_weekend",
    "is_holiday",
    "inventory_level",
    "lead_time_days",
    "stockout_flag",
    "minimum_order_quantity"
]

In [75]:
for col in integer_cols:
    df[col] = pd.to_numeric(
        df[col],
        downcast="integer"
    )

In [76]:
float_cols = [
    "sales_amount",
    "average_selling_price",
    "discount_percentage"
]

In [77]:
for col in float_cols:
    df[col] = pd.to_numeric(
        df[col],
        downcast="float"
    )

In [78]:
df[float_cols].dtypes

sales_amount             float64
average_selling_price    float32
discount_percentage      float32
dtype: object

In [79]:
memory_after = (
    df.memory_usage(deep=True).sum()
    / 1024**2
)

print(
    f"Memory Before: {memory_before:.2f} MB"
)

print(
    f"Memory After : {memory_after:.2f} MB"
)

print(
    f"Memory Saved : "
    f"{memory_before - memory_after:.2f} MB"
)

print(
    f"Reduction    : "
    f"{(1 - memory_after/memory_before)*100:.2f}%"
)

Memory Before: 1068.72 MB
Memory After : 59.18 MB
Memory Saved : 1009.54 MB
Reduction    : 94.46%

In [80]:
print("Shape:", df.shape)

Shape: (1000000, 35)

In [81]:
print("Date column type:", df["date"].dtype)
print("Start date:", df["date"].min())
print("End date:", df["date"].max())

Date column type: datetime64[ns]
Start date: 2025-07-01 00:00:00
End date: 2025-10-08 00:00:00

In [82]:
print("Unique Products :", df["product_id"].nunique())
print("Unique Stores   :", df["store_id"].nunique())
print("Unique Suppliers:", df["supplier_id"].nunique())

Unique Products : 200
Unique Stores   : 50
Unique Suppliers: 20

In [83]:
print(
    "Duplicate rows:",
    df.duplicated().sum()
)

Duplicate rows: 0

In [84]:
print(
    "Duplicate product-store-date:",
    df.duplicated(
        subset=["date", "product_id", "store_id"]
    ).sum()
)

Duplicate product-store-date: 0

In [85]:
missing = df.isnull().sum()

print(
    missing[missing > 0]
)

Series([], dtype: int64)

In [86]:
print("Negative quantity:",
      (df["quantity_sold"] < 0).sum())

print("Negative sales:",
      (df["sales_amount"] < 0).sum())

print("Negative inventory:",
      (df["inventory_level"] < 0).sum())

print("Invalid discount:",
      (
          (df["discount_percentage"] < 0) |
          (df["discount_percentage"] > 100)
      ).sum())

Negative quantity: 0
Negative sales: 0
Negative inventory: 0
Invalid discount: 0

In [87]:
binary_cols = [
    "is_promoted",
    "is_weekend",
    "is_holiday",
    "stockout_flag"
]

for col in binary_cols:
    print(
        f"{col}:",
        sorted(df[col].unique().tolist())
    )

is_promoted: [0, 1]
is_weekend: [0, 1]
is_holiday: [0, 1]
stockout_flag: [0, 1]

In [88]:
invalid_promotion = df[
    (df["is_promoted"] == 0) &
    (
        (df["promotion_type"] != "No Promotion") |
        (df["discount_percentage"] != 0)
    )
]

print(
    "Invalid promotion records:",
    len(invalid_promotion)
)

Invalid promotion records: 0

In [89]:
calculated_sales = (
    df["quantity_sold"] *
    df["average_selling_price"]
)

sales_difference = (
    df["sales_amount"] -
    calculated_sales
).abs()

print(
    "Maximum sales difference:",
    sales_difference.max()
)

Maximum sales difference: 0.05749999999534339

In [90]:
df = df.sort_values(
    ["product_id", "store_id", "date"]
).reset_index(drop=True)

In [91]:
df.head(10)[
    ["date", "product_id", "store_id", "quantity_sold"]
]

        date product_id store_id  quantity_sold
0 2025-07-01     P00001    S0001             71
1 2025-07-02     P00001    S0001             97
2 2025-07-03     P00001    S0001            125
3 2025-07-04     P00001    S0001             64
4 2025-07-05     P00001    S0001            134
5 2025-07-06     P00001    S0001            102
6 2025-07-07     P00001    S0001             87
7 2025-07-08     P00001    S0001             98
8 2025-07-09     P00001    S0001             58
9 2025-07-10     P00001    S0001            102

In [92]:
quality_checks = {
    "Correct shape": df.shape == (1_000_000, 35),

    "No missing values": df.isnull().sum().sum() == 0,

    "No duplicate rows": df.duplicated().sum() == 0,

    "No duplicate product-store-date": (
        df.duplicated(
            ["date", "product_id", "store_id"]
        ).sum() == 0
    ),

    "No negative quantity": (
        (df["quantity_sold"] < 0).sum() == 0
    ),

    "No negative sales": (
        (df["sales_amount"] < 0).sum() == 0
    ),

    "No negative inventory": (
        (df["inventory_level"] < 0).sum() == 0
    ),

    "Valid discount": (
        (
            (df["discount_percentage"] >= 0) &
            (df["discount_percentage"] <= 100)
        ).all()
    )
}

for check, result in quality_checks.items():
    print(
        f"{'✅' if result else '❌'} {check}: {result}"
    )

✅ Correct shape: True
✅ No missing values: True
✅ No duplicate rows: True
✅ No duplicate product-store-date: True
✅ No negative quantity: True
✅ No negative sales: True
✅ No negative inventory: True
✅ Valid discount: True

In [93]:
clean_path = "demandpulse_ai_clean.csv"

df.to_csv(
    clean_path,
    index=False
)

print(
    f"Clean dataset saved as: {clean_path}"
)

Clean dataset saved as: demandpulse_ai_clean.csv

In [94]:
df.to_pickle(
    "demandpulse_ai_clean.pkl"
)

In [95]:
df = pd.read_pickle(
    "demandpulse_ai_clean.pkl"
)

In [96]:
target = "future_demand"

In [97]:
df["future_demand"] = df["quantity_sold"].shift(-1)

In [98]:
df["future_demand"] = (
    df.groupby(
        ["product_id", "store_id"]
    )["quantity_sold"]
    .shift(-1)
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\3591176531.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

In [99]:
df = df.sort_values(
    ["product_id", "store_id", "date"]
).reset_index(drop=True)

In [100]:
df["future_demand"] = (
    df.groupby(
        ["product_id", "store_id"]
    )["quantity_sold"]
    .shift(-1)
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\3591176531.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

In [101]:
df[
    [
        "date",
        "product_id",
        "store_id",
        "quantity_sold",
        "future_demand"
    ]
].head(15)

         date product_id store_id  quantity_sold  future_demand
0  2025-07-01     P00001    S0001             71           97.0
1  2025-07-02     P00001    S0001             97          125.0
2  2025-07-03     P00001    S0001            125           64.0
3  2025-07-04     P00001    S0001             64          134.0
4  2025-07-05     P00001    S0001            134          102.0
5  2025-07-06     P00001    S0001            102           87.0
6  2025-07-07     P00001    S0001             87           98.0
7  2025-07-08     P00001    S0001             98           58.0
8  2025-07-09     P00001    S0001             58          102.0
9  2025-07-10     P00001    S0001            102           96.0
10 2025-07-11     P00001    S0001             96          118.0
11 2025-07-12     P00001    S0001            118           88.0
12 2025-07-13     P00001    S0001             88           68.0
13 2025-07-14     P00001    S0001             68           79.0
14 2025-07-15     P00001    S0001             79           76.0

In [102]:
print(
    "Future demand missing:",
    df["future_demand"].isna().sum()
)

Future demand missing: 10000

In [103]:
df["future_demand"].describe()

count    990000.000000
mean        119.877738
std          72.153535
min           2.000000
25%          64.000000
50%         105.000000
75%         160.000000
max        1000.000000
Name: future_demand, dtype: float64

In [104]:
print("Current demand mean:",
      df["quantity_sold"].mean())

print("Future demand mean:",
      df["future_demand"].mean())

Current demand mean: 119.628193
Future demand mean: 119.87773838383838

In [105]:
check = df[
    ["product_id", "store_id", "date",
     "quantity_sold", "future_demand"]
].copy()

check["expected_future"] = (
    check.groupby(
        ["product_id", "store_id"]
    )["quantity_sold"]
    .shift(-1)
)

print(
    "Target mismatches:",
    (
        check["future_demand"] !=
        check["expected_future"]
    ).sum()
)

Target mismatches: 10000

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\2561147627.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  check.groupby(

In [106]:
valid = (
    check["future_demand"].notna() &
    check["expected_future"].notna()
)

print(
    "Target mismatches:",
    (
        check.loc[valid, "future_demand"]
        !=
        check.loc[valid, "expected_future"]
    ).sum()
)

Target mismatches: 0

In [107]:
# ==========================================
# Forecasting Target Creation
# ==========================================

# Ensure chronological order
df = df.sort_values(
    ["product_id", "store_id", "date"]
).reset_index(drop=True)

# Next-day demand target
df["future_demand"] = (
    df.groupby(
        ["product_id", "store_id"]
    )["quantity_sold"]
    .shift(-1)
)

print("Target created successfully.")

print("\nTarget missing values:")
print(df["future_demand"].isna().sum())

print("\nTarget statistics:")
print(df["future_demand"].describe())

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1065476594.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(

Target created successfully.

Target missing values:
10000

Target statistics:
count    990000.000000
mean        119.877738
std          72.153535
min           2.000000
25%          64.000000
50%         105.000000
75%         160.000000
max        1000.000000
Name: future_demand, dtype: float64

In [108]:
df[
    (df["product_id"] == "P00001") &
    (df["store_id"] == "S0001")
][
    [
        "date",
        "quantity_sold",
        "future_demand"
    ]
].tail(10)

         date  quantity_sold  future_demand
90 2025-09-29             73           92.0
91 2025-09-30             92           91.0
92 2025-10-01             91           78.0
93 2025-10-02             78          153.0
94 2025-10-03            153          121.0
95 2025-10-04            121          176.0
96 2025-10-05            176           88.0
97 2025-10-06             88           82.0
98 2025-10-07             82           73.0
99 2025-10-08             73            NaN

In [109]:
group_cols = ["product_id", "store_id"]

In [110]:
for lag in [1, 3, 7, 14, 30]:
    df[f"sales_lag_{lag}"] = (
        df.groupby(group_cols)["quantity_sold"]
        .shift(lag)
    )

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1667456922.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1667456922.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1667456922.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1667456922.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1667456922.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]

In [111]:
# ==========================================
# Lag Features
# ==========================================

group_cols = ["product_id", "store_id"]

lag_periods = [1, 3, 7, 14, 30]

for lag in lag_periods:
    df[f"sales_lag_{lag}"] = (
        df.groupby(group_cols)["quantity_sold"]
        .shift(lag)
    )

print("Lag features created successfully.")

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\2806014414.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]

Lag features created successfully.

In [112]:
lag_cols = [
    "sales_lag_1",
    "sales_lag_3",
    "sales_lag_7",
    "sales_lag_14",
    "sales_lag_30"
]

df[lag_cols].head(35)

    sales_lag_1  sales_lag_3  sales_lag_7  sales_lag_14  sales_lag_30
0           NaN          NaN          NaN           NaN           NaN
1          71.0          NaN          NaN           NaN           NaN
2          97.0          NaN          NaN           NaN           NaN
3         125.0         71.0          NaN           NaN           NaN
4          64.0         97.0          NaN           NaN           NaN
5         134.0        125.0          NaN           NaN           NaN
6         102.0         64.0          NaN           NaN           NaN
7          87.0        134.0         71.0           NaN           NaN
8          98.0        102.0         97.0           NaN           NaN
9          58.0         87.0        125.0           NaN           NaN
10        102.0         98.0         64.0           NaN           NaN
11         96.0         58.0        134.0           NaN           NaN
12        118.0        102.0        102.0           NaN           NaN
13         88.0         96.0         87.0           NaN           NaN
14         68.0        118.0         98.0          71.0           NaN
15         79.0         88.0         58.0          97.0           NaN
16         76.0         68.0        102.0         125.0           NaN
17        105.0         79.0         96.0          64.0           NaN
18         66.0         76.0        118.0         134.0           NaN
19        120.0        105.0         88.0         102.0           NaN
20        130.0         66.0         68.0          87.0           NaN
21         83.0        120.0         79.0          98.0           NaN
22         93.0        130.0         76.0          58.0           NaN
23         92.0         83.0        105.0         102.0           NaN
24        103.0         93.0         66.0          96.0           NaN
25         60.0         92.0        120.0         118.0           NaN
26        110.0        103.0        130.0          88.0           NaN
27         51.0         60.0         83.0          68.0           NaN
28         66.0        110.0         93.0          79.0           NaN
29         75.0         51.0         92.0          76.0           NaN
30        103.0         66.0        103.0         105.0          71.0
31         78.0         75.0         60.0          66.0          97.0
32         78.0        103.0        110.0         120.0         125.0
33         75.0         78.0         51.0         130.0          64.0
34         80.0         78.0         66.0          83.0         134.0

In [113]:
sample_series = df[
    (df["product_id"] == "P00001") &
    (df["store_id"] == "S0001")
][
    [
        "date",
        "quantity_sold",
        "sales_lag_1",
        "sales_lag_3",
        "sales_lag_7",
        "sales_lag_14",
        "sales_lag_30"
    ]
]

sample_series.head(35)

,date,quantity_sold,sales_lag_1,sales_lag_3,sales_lag_7,sales_lag_14,sales_lag_30
0,2025-07-01,71,NaN,NaN,NaN,NaN,NaN
1,2025-07-02,97,71.0,NaN,NaN,NaN,NaN
2,2025-07-03,125,97.0,NaN,NaN,NaN,NaN
3,2025-07-04,64,125.0,71.0,NaN,NaN,NaN
4,2025-07-05,134,64.0,97.0,NaN,NaN,NaN
5,2025-07-06,102,134.0,125.0,NaN,NaN,NaN
6,2025-07-07,87,102.0,64.0,NaN,NaN,NaN
7,2025-07-08,98,87.0,134.0,71.0,NaN,NaN
8,2025-07-09,58,98.0,102.0,97.0,NaN,NaN
9,2025-07-10,102,58.0,87.0,125.0,NaN,NaN
10,2025-07-11,96,102.0,98.0,64.0,NaN,NaN
11,2025-07-12,118,96.0,58.0,134.0,NaN,NaN
12,2025-07-13,88,118.0,102.0,102.0,NaN,NaN
13,2025-07-14,68,88.0,96.0,87.0,NaN,NaN
14,2025-07-15,79,68.0,118.0,98.0,71.0,NaN
15,2025-07-16,76,79.0,88.0,58.0,97.0,NaN
16,2025-07-17,105,76.0,68.0,102.0,125.0,NaN
17,2025-07-18,66,105.0,79.0,96.0,64.0,NaN
18,2025-07-19,120,66.0,76.0,118.0,134.0,NaN
19,2025-07-20,130,120.0,105.0,88.0,102.0,NaN
20,2025-07-21,83,130.0,66.0,68.0,87.0,NaN
21,2025-07-22,93,83.0,120.0,79.0,98.0,NaN
22,2025-07-23,92,93.0,130.0,76.0,58.0,NaN
23,2025-07-24,103,92.0,83.0,105.0,102.0,NaN
24,2025-07-25,60,103.0,93.0,66.0,96.0,NaN
25,2025-07-26,110,60.0,92.0,120.0,118.0,NaN
26,2025-07-27,51,110.0,103.0,130.0,88.0,NaN
27,2025-07-28,66,51.0,60.0,83.0,68.0,NaN
28,2025-07-29,75,66.0,110.0,93.0,79.0,NaN
29,2025-07-30,103,75.0,51.0,92.0,76.0,NaN
30,2025-07-31,78,103.0,66.0,103.0,105.0,71.0
31,2025-08-01,78,78.0,75.0,60.0,66.0,97.0
32,2025-08-02,75,78.0,103.0,110.0,120.0,125.0
33,2025-08-03,80,75.0,78.0,51.0,130.0,64.0
34,2025-08-04,62,80.0,78.0,66.0,83.0,134.0

In [114]:
for col in lag_cols:
    print(
        col,
        "missing:",
        df[col].isna().sum()
    )

sales_lag_1 missing: 10000
sales_lag_3 missing: 30000
sales_lag_7 missing: 70000
sales_lag_14 missing: 140000
sales_lag_30 missing: 300000

In [115]:
for col in lag_cols:
    print(
        col,
        "missing:",
        df[col].isna().sum()
    )

sales_lag_1 missing: 10000
sales_lag_3 missing: 30000
sales_lag_7 missing: 70000
sales_lag_14 missing: 140000
sales_lag_30 missing: 300000

In [116]:
group_cols = ["product_id", "store_id"]

df["rolling_mean_7"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(7).mean())
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\551033879.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]

In [117]:
group_cols = ["product_id", "store_id"]

# Rolling Mean
df["rolling_mean_7"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(7).mean())
)

df["rolling_mean_14"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(14).mean())
)

df["rolling_mean_30"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(30).mean())
)

# Rolling Standard Deviation
df["rolling_std_7"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(7).std())
)

df["rolling_std_30"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(30).std())
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\836049186.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\836049186.py:10: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\836049186.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\836049186.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\836049186.py:26: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]

In [118]:
rolling_cols = [
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_30",
    "rolling_std_7",
    "rolling_std_30"
]

df[rolling_cols].head(35)

,rolling_mean_7,rolling_mean_14,rolling_mean_30,rolling_std_7,rolling_std_30
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN
7,97.142857,NaN,NaN,25.957841,NaN
8,101.000000,NaN,NaN,23.295207,NaN
9,95.428571,NaN,NaN,28.494778,NaN
10,92.142857,NaN,NaN,25.706216,NaN
11,96.714286,NaN,NaN,22.514546,NaN
12,94.428571,NaN,NaN,18.563918,NaN
13,92.428571,NaN,NaN,18.365340,NaN
14,89.714286,93.428571,NaN,20.572751,NaN
15,87.000000,94.000000,NaN,20.550750,NaN
16,89.571429,92.500000,NaN,17.164471,NaN
17,90.000000,91.071429,NaN,17.559423,NaN
18,85.714286,91.214286,NaN,19.414035,NaN
19,86.000000,90.214286,NaN,19.974984,NaN
20,92.000000,92.214286,NaN,26.057628,NaN
21,94.142857,91.928571,NaN,24.313430,NaN
22,96.142857,91.571429,NaN,23.419569,NaN
23,98.428571,94.000000,NaN,21.854497,NaN
24,98.142857,94.071429,NaN,21.767166,NaN
25,97.285714,91.500000,NaN,23.307469,NaN
26,95.857143,90.928571,NaN,21.950160,NaN
27,84.571429,88.285714,NaN,21.778102,NaN
28,82.142857,88.142857,NaN,22.901445,NaN
29,79.571429,87.857143,NaN,22.485974,NaN
30,81.142857,89.785714,90.666667,23.842739,22.412025
31,77.571429,87.857143,90.900000,21.808692,22.235960
32,80.142857,88.714286,90.266667,20.407748,22.326624
33,75.142857,85.500000,88.600000,15.593039,21.495148
34,79.285714,81.928571,89.133333,11.397577,21.057775

In [119]:
df[rolling_cols].isna().sum()

rolling_mean_7      70000
rolling_mean_14    140000
rolling_mean_30    300000
rolling_std_7       70000
rolling_std_30     300000
dtype: int64

In [120]:
df["demand_change_1"] = (
    df.groupby(["product_id", "store_id"])["quantity_sold"]
      .diff(1)
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\248874680.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["product_id", "store_id"])["quantity_sold"]

In [121]:
df["demand_change_7"] = (
    df.groupby(["product_id", "store_id"])["quantity_sold"]
      .diff(7)
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\394356167.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["product_id", "store_id"])["quantity_sold"]

In [122]:
df["demand_change_7"] = (
    df.groupby(["product_id", "store_id"])["quantity_sold"]
      .diff(7)
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\394356167.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["product_id", "store_id"])["quantity_sold"]

In [123]:
df["demand_ratio_7"] = (
    df["quantity_sold"] /
    df["rolling_mean_7"]
)

In [124]:
trend_cols = [
    "demand_change_1",
    "demand_change_7",
    "growth_rate_7",
    "demand_ratio_7"
]

[col for col in trend_cols if col not in df.columns]

['growth_rate_7']

In [125]:
group_cols = ["product_id", "store_id"]

df["growth_rate_7"] = (
    df["quantity_sold"] /
    df.groupby(group_cols)["quantity_sold"].shift(7)
    - 1
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\58483000.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"].shift(7)

In [126]:
df[trend_cols].head(20)

    demand_change_1  demand_change_7  growth_rate_7  demand_ratio_7
0               NaN              NaN            NaN             NaN
1              26.0              NaN            NaN             NaN
2              28.0              NaN            NaN             NaN
3             -61.0              NaN            NaN             NaN
4              70.0              NaN            NaN             NaN
5             -32.0              NaN            NaN             NaN
6             -15.0              NaN            NaN             NaN
7              11.0             27.0       0.380282        1.008824
8             -40.0            -39.0      -0.402062        0.574257
9              44.0            -23.0      -0.184000        1.068862
10             -6.0             32.0       0.500000        1.041860
11             22.0            -16.0      -0.119403        1.220089
12            -30.0            -14.0      -0.137255        0.931921
13            -20.0            -19.0      -0.218391        0.735703
14             11.0            -19.0      -0.193878        0.880573
15             -3.0             18.0       0.310345        0.873563
16             29.0              3.0       0.029412        1.172249
17            -39.0            -30.0      -0.312500        0.733333
18             54.0              2.0       0.016949        1.400000
19             10.0             42.0       0.477273        1.511628

In [127]:
import numpy as np

day_map = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6
}

# 1. Convert day name → numeric
df["day_of_week_num"] = (
    df["day_of_week"]
    .astype(str)
    .map(day_map)
    .astype("int8")
)

# 2. Weekend
df["is_weekend_calc"] = (
    df["day_of_week_num"] >= 5
).astype("int8")

In [128]:
df[[
    "day_of_week",
    "day_of_week_num",
    "is_weekend",
    "is_weekend_calc"
]].head(15)

   day_of_week  day_of_week_num  is_weekend  is_weekend_calc
0      Tuesday                1           0                0
1    Wednesday                2           0                0
2     Thursday                3           0                0
3       Friday                4           0                0
4     Saturday                5           1                1
5       Sunday                6           1                1
6       Monday                0           0                0
7      Tuesday                1           0                0
8    Wednesday                2           0                0
9     Thursday                3           0                0
10      Friday                4           0                0
11    Saturday                5           1                1
12      Sunday                6           1                1
13      Monday                0           0                0
14     Tuesday                1           0                0

In [129]:
(df["is_weekend"] == df["is_weekend_calc"]).value_counts()

True    1000000
Name: count, dtype: int64

In [130]:
df["is_month_start"] = df["date"].dt.is_month_start.astype("int8")

df["is_month_end"] = df["date"].dt.is_month_end.astype("int8")

In [131]:
df["is_week_start"] = (
    df["date"].dt.dayofweek == 0
).astype("int8")

df["is_week_end"] = (
    df["date"].dt.dayofweek == 6
).astype("int8")

In [132]:
import numpy as np

df["day_of_week_sin"] = np.sin(
    2 * np.pi * df["day_of_week_num"] / 7
)

df["day_of_week_cos"] = np.cos(
    2 * np.pi * df["day_of_week_num"] / 7
)

In [133]:
df["month_sin"] = np.sin(
    2 * np.pi * (df["month"] - 1) / 12
)

df["month_cos"] = np.cos(
    2 * np.pi * (df["month"] - 1) / 12
)

In [134]:
df["has_special_event"] = (
    df["special_event"] != "No Event"
).astype("int8")

In [135]:
df["has_holiday"] = (
    df["holiday_name"] != "No Holiday"
).astype("int8")

In [136]:
calendar_features = [
    "day_of_week_num",
    "is_weekend_calc",
    "is_month_start",
    "is_month_end",
    "is_week_start",
    "is_week_end",
    "day_of_week_sin",
    "day_of_week_cos",
    "month_sin",
    "month_cos",
    "has_holiday",
    "has_special_event"
]

df[calendar_features].head(15)

,day_of_week_num,is_weekend_calc,is_month_start,is_month_end,is_week_start,is_week_end,day_of_week_sin,day_of_week_cos,month_sin,month_cos,has_holiday,has_special_event
0,1,0,1,0,0,0,0.781831,0.623490,1.224647e-16,-1.0,0,0
1,2,0,0,0,0,0,0.974928,-0.222521,1.224647e-16,-1.0,0,0
2,3,0,0,0,0,0,0.433884,-0.900969,1.224647e-16,-1.0,0,0
3,4,0,0,0,0,0,-0.433884,-0.900969,1.224647e-16,-1.0,0,0
4,5,1,0,0,0,0,-0.974928,-0.222521,1.224647e-16,-1.0,0,0
5,6,1,0,0,0,1,-0.781831,0.623490,1.224647e-16,-1.0,0,0
6,0,0,0,0,1,0,0.000000,1.000000,1.224647e-16,-1.0,0,0
7,1,0,0,0,0,0,0.781831,0.623490,1.224647e-16,-1.0,0,0
8,2,0,0,0,0,0,0.974928,-0.222521,1.224647e-16,-1.0,0,0
9,3,0,0,0,0,0,0.433884,-0.900969,1.224647e-16,-1.0,0,0
10,4,0,0,0,0,0,-0.433884,-0.900969,1.224647e-16,-1.0,0,0
11,5,1,0,0,0,0,-0.974928,-0.222521,1.224647e-16,-1.0,0,0
12,6,1,0,0,0,1,-0.781831,0.623490,1.224647e-16,-1.0,0,0
13,0,0,0,0,1,0,0.000000,1.000000,1.224647e-16,-1.0,0,0
14,1,0,0,0,0,0,0.781831,0.623490,1.224647e-16,-1.0,0,0

In [137]:
(df["is_weekend"] == df["is_weekend_calc"]).value_counts()

True    1000000
Name: count, dtype: int64

In [138]:
df[["holiday_name", "has_holiday"]].drop_duplicates()

        holiday_name  has_holiday
0         No Holiday            0
45  Independence Day            1
57  Ganesh Chaturthi            1

In [139]:
df[["special_event", "has_special_event"]].drop_duplicates()

       special_event  has_special_event
0           No Event                  0
45  Independence Day                  1
57          Festival                  1

In [140]:
df.drop(columns=["is_weekend_calc"], inplace=True)

In [141]:
df["effective_price"] = (
    df["average_selling_price"] *
    (1 - df["discount_percentage"] / 100)
)

In [142]:
df["promotion_discount"] = (
    df["is_promoted"] *
    df["discount_percentage"]
)

In [143]:
group_cols = ["product_id", "store_id"]

df["price_lag_1"] = (
    df.groupby(group_cols)["average_selling_price"]
      .shift(1)
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1829308583.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["average_selling_price"]

In [144]:
df["price_change_1"] = (
    df["average_selling_price"] -
    df["price_lag_1"]
)

In [145]:
df["price_change_pct_1"] = (
    (df["average_selling_price"] / df["price_lag_1"]) - 1
)

In [146]:
price_features = [
    "effective_price",
    "promotion_discount",
    "price_lag_1",
    "price_change_1",
    "price_change_pct_1"
]

df[price_features].head(20)

,effective_price,promotion_discount,price_lag_1,price_change_1,price_change_pct_1
0,615.640625,6.520000,NaN,NaN,NaN
1,743.989990,0.000000,658.580017,85.409973,0.129688
2,713.599976,0.000000,743.989990,-30.390015,-0.040847
3,733.950012,0.000000,713.599976,20.350037,0.028517
4,391.747467,26.540001,733.950012,-200.669983,-0.273411
5,736.520020,0.000000,533.280029,203.239990,0.381113
6,709.210022,0.000000,736.520020,-27.309998,-0.037080
7,554.723999,12.070000,709.210022,-78.340027,-0.110461
8,723.239990,0.000000,630.869995,92.369995,0.146417
9,717.630005,0.000000,723.239990,-5.609985,-0.007757
10,735.169983,0.000000,717.630005,17.539978,0.024441
11,710.849976,0.000000,735.169983,-24.320007,-0.033081
12,704.630005,0.000000,710.849976,-6.219971,-0.008750
13,722.630005,0.000000,704.630005,18.000000,0.025545
14,729.789978,0.000000,722.630005,7.159973,0.009908
15,713.619995,0.000000,729.789978,-16.169983,-0.022157
16,707.500000,0.000000,713.619995,-6.119995,-0.008576
17,735.659973,0.000000,707.500000,28.159973,0.039802
18,710.679993,0.000000,735.659973,-24.979980,-0.033956
19,576.397888,10.500000,710.679993,-66.659973,-0.093797

In [147]:
df[price_features].describe()

,effective_price,promotion_discount,price_lag_1,price_change_1,price_change_pct_1
count,1000000.000000,1000000.000000,990000.000000,990000.000000,990000.000000
mean,574.907898,2.607131,587.571716,-0.006262,0.006031
std,357.282227,6.643016,358.233521,68.407265,0.111820
min,9.147558,0.000000,15.090000,-495.640076,-0.428843
25%,266.829788,0.000000,272.019989,-13.192535,-0.026238
50%,520.368835,0.000000,559.539978,0.000000,0.000000
75%,895.909973,0.000000,912.919983,13.179993,0.026926
max,1231.930054,40.000000,1231.930054,500.329956,0.749646

In [148]:
group_cols = ["product_id", "store_id"]

In [149]:
# --------------------------------
# 1. Inventory Coverage
# --------------------------------

df["inventory_coverage_days"] = (
    df["inventory_level"] /
    df["rolling_mean_7"]
)

In [150]:
# --------------------------------
# 2. Lead-Time Demand
# --------------------------------

df["lead_time_demand"] = (
    df["rolling_mean_7"] *
    df["lead_time_days"]
)

In [151]:
# --------------------------------
# 3. Inventory Gap
# --------------------------------

df["inventory_gap"] = (
    df["inventory_level"] -
    df["lead_time_demand"]
)

In [152]:
# --------------------------------
# 4. Potential Stockout Risk
# --------------------------------

df["potential_stockout_risk"] = (
    df["inventory_level"] <
    df["lead_time_demand"]
).astype("int8")

In [153]:
# --------------------------------
# 5. MOQ / Inventory Ratio
# --------------------------------

df["moq_inventory_ratio"] = (
    df["minimum_order_quantity"] /
    df["inventory_level"].replace(0, np.nan)
)

In [154]:
# Validation
# Features check

inventory_features = [
    "inventory_coverage_days",
    "lead_time_demand",
    "inventory_gap",
    "potential_stockout_risk",
    "moq_inventory_ratio"
]

df[inventory_features].head(20)

,inventory_coverage_days,lead_time_demand,inventory_gap,potential_stockout_risk,moq_inventory_ratio
0,NaN,NaN,NaN,0,0.165563
1,NaN,NaN,NaN,0,0.534759
2,NaN,NaN,NaN,0,0.178571
3,NaN,NaN,NaN,0,0.078740
4,NaN,NaN,NaN,0,0.077399
5,NaN,NaN,NaN,0,0.284091
6,NaN,NaN,NaN,0,0.381679
7,1.657353,485.714286,-324.714286,1,0.310559
8,2.792079,707.000000,-425.000000,1,0.177305
9,1.456587,190.857143,-51.857143,1,0.179856
10,2.897674,460.714286,-193.714286,1,0.374532
11,2.698671,386.857143,-125.857143,1,0.095785
12,3.293495,283.285714,27.714286,0,0.643087
13,3.040185,369.714286,-88.714286,1,0.177936
14,2.329618,628.000000,-419.000000,1,0.119617
15,3.011494,609.000000,-347.000000,1,0.286260
16,3.561404,268.714286,50.285714,0,0.078370
17,2.011111,180.000000,1.000000,0,0.414365
18,3.406667,342.857143,-50.857143,1,0.085616
19,2.604651,172.000000,52.000000,0,0.111607

In [155]:
df[inventory_features].describe()

,inventory_coverage_days,lead_time_demand,inventory_gap,potential_stockout_risk,moq_inventory_ratio
count,930000.000000,930000.000000,930000.000000,1000000.000000,1000000.000000
mean,2.709514,484.556151,-163.813798,0.652321,0.382476
std,1.033725,386.283571,333.023007,0.476234,0.776210
min,0.135266,12.285714,-3877.285714,0.000000,0.005165
25%,2.014634,211.428571,-282.000000,0.000000,0.085324
50%,2.688581,380.000000,-95.142857,1.000000,0.187266
75%,3.383333,640.000000,24.857143,1.000000,0.403226
max,9.836327,4292.857143,1456.285714,1.000000,50.000000

In [156]:
df[inventory_features].isna().sum()

inventory_coverage_days    70000
lead_time_demand           70000
inventory_gap              70000
potential_stockout_risk        0
moq_inventory_ratio            0
dtype: int64

In [157]:
group_cols = ["product_id", "store_id"]

In [158]:
# --------------------------------
# 1. 7-Day Demand CV
# --------------------------------

df["demand_cv_7"] = (
    df["rolling_std_7"] /
    df["rolling_mean_7"]
)

In [159]:
# --------------------------------
# 2. 14-Day Rolling Std
# --------------------------------

df["rolling_std_14"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(14).std())
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1545684782.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(group_cols)["quantity_sold"]

In [160]:
# --------------------------------
# 3. 14-Day Demand CV
# --------------------------------

df["demand_cv_14"] = (
    df["rolling_std_14"] /
    df["rolling_mean_14"]
)

In [161]:
# --------------------------------
# 4. Recent vs Long-Term Demand
# --------------------------------

df["recent_vs_longterm_demand"] = (
    df["rolling_mean_7"] /
    df["rolling_mean_30"]
)

In [162]:
# --------------------------------
# 5. Demand Momentum
# --------------------------------

df["demand_momentum_7"] = (
    df["rolling_mean_7"] -
    df["rolling_mean_14"]
)

In [163]:
# Validation
# Features check

volatility_features = [
    "demand_cv_7",
    "rolling_std_14",
    "demand_cv_14",
    "recent_vs_longterm_demand",
    "demand_momentum_7"
]

df[volatility_features].head(35)

,demand_cv_7,rolling_std_14,demand_cv_14,recent_vs_longterm_demand,demand_momentum_7
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN
7,0.267213,NaN,NaN,NaN,NaN
8,0.230646,NaN,NaN,NaN,NaN
9,0.298598,NaN,NaN,NaN,NaN
10,0.278982,NaN,NaN,NaN,NaN
11,0.232794,NaN,NaN,NaN,NaN
12,0.196592,NaN,NaN,NaN,NaN
13,0.198698,NaN,NaN,NaN,NaN
14,0.229314,22.829516,0.244353,NaN,-3.714286
15,0.236216,22.319360,0.237440,NaN,-7.000000
16,0.191629,22.802665,0.246515,NaN,-2.928571
17,0.195105,21.178597,0.232549,NaN,-1.071429
18,0.226497,20.987830,0.230094,NaN,-5.500000
19,0.232267,19.035103,0.210999,NaN,-4.214286
20,0.283235,21.658818,0.234875,NaN,-0.214286
21,0.258261,21.759045,0.236695,NaN,2.214286
22,0.243591,21.692658,0.236893,NaN,4.571429
23,0.222034,19.430349,0.206706,NaN,4.428571
24,0.221791,19.463830,0.206905,NaN,4.071429
25,0.239578,21.464640,0.234586,NaN,5.785714
26,0.228988,20.801125,0.228763,NaN,4.928571
27,0.257511,23.391085,0.264948,NaN,-3.714286
28,0.278800,23.530200,0.266955,NaN,-6.000000
29,0.282589,23.673605,0.269456,NaN,-8.285714
30,0.293837,23.733062,0.264330,0.894958,-8.642857
31,0.281143,23.497486,0.267451,0.853371,-10.285714
32,0.254642,22.848762,0.257554,0.887846,-8.571429
33,0.207512,21.215923,0.248139,0.848114,-10.357143
34,0.143753,16.922740,0.206555,0.889518,-2.642857

In [164]:
df[volatility_features].describe()

,demand_cv_7,rolling_std_14,demand_cv_14,recent_vs_longterm_demand,demand_momentum_7
count,930000.000000,860000.000000,860000.000000,700000.000000,860000.000000
mean,0.257483,31.396599,0.263905,1.029201,1.158259
std,0.093142,18.569800,0.066675,0.087329,9.084295
min,0.020515,1.703261,0.061335,0.609185,-80.428571
25%,0.189024,17.077232,0.215241,0.970874,-3.357143
50%,0.243987,27.642935,0.258421,1.028053,0.857143
75%,0.315572,41.703411,0.306181,1.086534,5.428571
max,0.904138,209.984039,0.670507,1.493161,87.071429

In [165]:
df[volatility_features].isna().sum()

demand_cv_7                   70000
rolling_std_14               140000
demand_cv_14                 140000
recent_vs_longterm_demand    300000
demand_momentum_7            140000
dtype: int64

In [166]:
print("Dataset Shape:", df.shape)
print("Total Features:", len(df.columns))

Dataset Shape: (1000000, 76)
Total Features: 76

In [167]:
# Engineered Features List

In [168]:
engineered_features = [
    "future_demand",

    # Lag
    "sales_lag_1",
    "sales_lag_3",
    "sales_lag_7",
    "sales_lag_14",
    "sales_lag_30",

    # Rolling
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_30",
    "rolling_std_7",
    "rolling_std_30",
    "rolling_std_14",

    # Trend
    "demand_change_1",
    "demand_change_7",
    "growth_rate_7",
    "demand_ratio_7",

    # Calendar
    "day_of_week_num",
    "is_month_start",
    "is_month_end",
    "is_week_start",
    "is_week_end",
    "day_of_week_sin",
    "day_of_week_cos",
    "month_sin",
    "month_cos",
    "has_holiday",
    "has_special_event",

    # Price / Promotion
    "effective_price",
    "promotion_discount",
    "price_lag_1",
    "price_change_1",
    "price_change_pct_1",

    # Inventory / Supply
    "inventory_coverage_days",
    "lead_time_demand",
    "inventory_gap",
    "potential_stockout_risk",
    "moq_inventory_ratio",

    # Volatility
    "demand_cv_7",
    "demand_cv_14",
    "recent_vs_longterm_demand",
    "demand_momentum_7"
]

print("Engineered columns:", len(engineered_features))

Engineered columns: 41

In [169]:
missing_features = [
    col for col in engineered_features
    if col not in df.columns
]

print("Missing engineered features:")
print(missing_features)

Missing engineered features:
[]

In [170]:
nan_summary = df.isna().sum()

nan_summary = (
    nan_summary[nan_summary > 0]
    .sort_values(ascending=False)
)

print(nan_summary)

recent_vs_longterm_demand    300000
sales_lag_30                 300000
rolling_mean_30              300000
rolling_std_30               300000
demand_momentum_7            140000
demand_cv_14                 140000
sales_lag_14                 140000
rolling_std_14               140000
rolling_mean_14              140000
growth_rate_7                 70000
demand_cv_7                   70000
inventory_gap                 70000
lead_time_demand              70000
inventory_coverage_days       70000
demand_ratio_7                70000
demand_change_7               70000
rolling_std_7                 70000
rolling_mean_7                70000
sales_lag_7                   70000
sales_lag_3                   30000
price_lag_1                   10000
price_change_1                10000
price_change_pct_1            10000
sales_lag_1                   10000
demand_change_1               10000
future_demand                 10000
dtype: int64

In [171]:
numeric_df = df.select_dtypes(include=np.number)

inf_count = np.isinf(numeric_df).sum()

print(
    inf_count[inf_count > 0]
)

Series([], dtype: int64)

In [172]:
target = "future_demand"

In [173]:
feature_candidates = [
    col for col in df.columns
    if col != target
]

print("Target:", target)
print("Target in features:", target in feature_candidates)

Target: future_demand
Target in features: False

In [174]:
df.drop(columns=["year"], inplace=True)

In [175]:
constant_features = [
    col for col in df.columns
    if df[col].nunique(dropna=False) <= 1
]

print(constant_features)

[]

In [176]:
print("is_holiday:")
print(df["is_holiday"].value_counts(dropna=False))

print("\nhas_holiday:")
print(df["has_holiday"].value_counts(dropna=False))

print("\nhas_special_event:")
print(df["has_special_event"].value_counts(dropna=False))

print("\nspecial_event:")
print(df["special_event"].value_counts(dropna=False))

is_holiday:
is_holiday
0    970000
1     30000
Name: count, dtype: int64

has_holiday:
has_holiday
0    970000
1     30000
Name: count, dtype: int64

has_special_event:
has_special_event
0    970000
1     30000
Name: count, dtype: int64

special_event:
special_event
No Event            970000
Independence Day     20000
Festival             10000
Name: count, dtype: int64

In [177]:
print(
    df[
        [
            "is_holiday",
            "has_holiday",
            "special_event",
            "has_special_event"
        ]
    ].drop_duplicates().sort_values(
        ["is_holiday", "has_holiday", "special_event"]
    )
)

    is_holiday  has_holiday     special_event  has_special_event
0            0            0          No Event                  0
57           1            1          Festival                  1
45           1            1  Independence Day                  1

In [178]:
df.drop(columns=["has_holiday"], inplace=True)

In [179]:
df[[
    "is_promoted",
    "discount_percentage",
    "promotion_discount"
]].drop_duplicates()

        is_promoted  discount_percentage  promotion_discount
0                 1             6.520000            6.520000
1                 0             0.000000            0.000000
4                 1            26.540001           26.540001
7                 1            12.070000           12.070000
19                1            10.500000           10.500000
...             ...                  ...                 ...
750005            1            36.599998           36.599998
755787            1            39.099998           39.099998
778139            1            32.270000           32.270000
823987            1            39.820000           39.820000
862140            1            36.470001           36.470001

[3501 rows x 3 columns]

In [180]:
df.drop(columns=["promotion_discount"], inplace=True)

In [181]:
print("Duplicate column pairs after removing has_holiday:")

duplicate_columns = []

columns = df.columns

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):
        if df[columns[i]].equals(df[columns[j]]):
            duplicate_columns.append(
                (columns[i], columns[j])
            )

print(duplicate_columns)

Duplicate column pairs after removing has_holiday:
[('is_holiday', 'has_special_event')]

In [182]:
# Remove duplicate feature
df.drop(columns=["has_special_event"], inplace=True)

print("has_special_event" in df.columns)

False

In [183]:
duplicate_columns = []

columns = df.columns

for i in range(len(columns)):
    for j in range(i + 1, len(columns)):
        if df[columns[i]].equals(df[columns[j]]):
            duplicate_columns.append(
                (columns[i], columns[j])
            )

print("Duplicate column pairs:")
print(duplicate_columns)

Duplicate column pairs:
[]

In [184]:
print("Negative target values:",
      (df["future_demand"] < 0).sum())

print("Target missing values:",
      df["future_demand"].isna().sum())

print("Target statistics:")
print(df["future_demand"].describe())

Negative target values: 0
Target missing values: 10000
Target statistics:
count    990000.000000
mean        119.877738
std          72.153535
min           2.000000
25%          64.000000
50%         105.000000
75%         160.000000
max        1000.000000
Name: future_demand, dtype: float64

In [185]:
audit = pd.DataFrame({
    "dtype": df.dtypes.astype(str),
    "missing_count": df.isna().sum(),
    "missing_percent": (
        df.isna().mean() * 100
    ).round(2),
    "unique_values": df.nunique()
})

audit.sort_values(
    "missing_count",
    ascending=False
).head(20)

,dtype,missing_count,missing_percent,unique_values
rolling_std_30,float64,300000,30.0,619063
recent_vs_longterm_demand,float64,300000,30.0,403561
sales_lag_30,float64,300000,30.0,602
rolling_mean_30,float64,300000,30.0,9868
demand_momentum_7,float64,140000,14.0,6471
rolling_mean_14,float64,140000,14.0,4971
sales_lag_14,float64,140000,14.0,613
rolling_std_14,float64,140000,14.0,664048
demand_cv_14,float64,140000,14.0,840147
lead_time_demand,float64,70000,7.0,10444
inventory_coverage_days,float64,70000,7.0,316117
sales_lag_7,float64,70000,7.0,624
demand_ratio_7,float64,70000,7.0,164171
demand_change_7,float32,70000,7.0,787
inventory_gap,float64,70000,7.0,36965
rolling_std_7,float64,70000,7.0,547681
demand_cv_7,float64,70000,7.0,899105
rolling_mean_7,float64,70000,7.0,2697
growth_rate_7,float64,70000,7.0,53737
sales_lag_3,float64,30000,3.0,636

In [186]:
nan_report = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

print(nan_report[nan_report > 0])

rolling_std_30               300000
recent_vs_longterm_demand    300000
sales_lag_30                 300000
rolling_mean_30              300000
demand_momentum_7            140000
rolling_mean_14              140000
sales_lag_14                 140000
rolling_std_14               140000
demand_cv_14                 140000
lead_time_demand              70000
inventory_coverage_days       70000
sales_lag_7                   70000
demand_ratio_7                70000
demand_change_7               70000
inventory_gap                 70000
rolling_std_7                 70000
demand_cv_7                   70000
rolling_mean_7                70000
growth_rate_7                 70000
sales_lag_3                   30000
price_lag_1                   10000
sales_lag_1                   10000
demand_change_1               10000
price_change_pct_1            10000
price_change_1                10000
future_demand                 10000
dtype: int64

In [187]:
numeric_cols = df.select_dtypes(include=np.number).columns

df[numeric_cols] = df[numeric_cols].replace(
    [np.inf, -np.inf],
    np.nan
)

In [188]:
print(df["future_demand"].isna().sum())

10000

In [189]:
df = df.dropna(subset=["future_demand"]).copy()

In [190]:
remaining_nan = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
)

print(remaining_nan[remaining_nan > 0])

rolling_std_30               300000
recent_vs_longterm_demand    300000
sales_lag_30                 300000
rolling_mean_30              300000
demand_momentum_7            140000
rolling_mean_14              140000
sales_lag_14                 140000
rolling_std_14               140000
demand_cv_14                 140000
lead_time_demand              70000
inventory_coverage_days       70000
sales_lag_7                   70000
demand_ratio_7                70000
demand_change_7               70000
inventory_gap                 70000
rolling_std_7                 70000
demand_cv_7                   70000
rolling_mean_7                70000
growth_rate_7                 70000
sales_lag_3                   30000
price_lag_1                   10000
sales_lag_1                   10000
demand_change_1               10000
price_change_pct_1            10000
price_change_1                10000
dtype: int64

In [191]:
df.dropna()

,date,day_of_week,day_of_month,week_of_year,month,quarter,product_id,product_name,category,subcategory,...,inventory_coverage_days,lead_time_demand,inventory_gap,potential_stockout_risk,moq_inventory_ratio,demand_cv_7,rolling_std_14,demand_cv_14,recent_vs_longterm_demand,demand_momentum_7
30,2025-07-31,Thursday,31,31,7,3,P00001,Brand_C Detergent Product 001,Household,Detergent,...,2.316901,324.571429,-136.571429,1,0.531915,0.293837,23.733062,0.264330,0.894958,-8.642857
31,2025-08-01,Friday,1,31,8,3,P00001,Brand_C Detergent Product 001,Household,Detergent,...,2.307551,232.714286,-53.714286,1,0.418994,0.281143,23.497486,0.267451,0.853371,-10.285714
32,2025-08-02,Saturday,2,31,8,3,P00001,Brand_C Detergent Product 001,Household,Detergent,...,3.768271,561.000000,-259.000000,1,0.033113,0.254642,22.848762,0.257554,0.887846,-8.571429
33,2025-08-03,Sunday,3,31,8,3,P00001,Brand_C Detergent Product 001,Household,Detergent,...,3.566540,225.428571,42.571429,0,0.279851,0.207512,21.215923,0.248139,0.848114,-10.357143
34,2025-08-04,Monday,4,32,8,3,P00001,Brand_C Detergent Product 001,Household,Detergent,...,2.724324,317.142857,-101.142857,1,0.115741,0.143753,16.922740,0.206555,0.889518,-2.642857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999994,2025-10-03,Friday,3,40,10,4,P00200,Brand_E Tea Product 200,Beverages,Tea,...,4.584795,293.142857,154.857143,0,0.022321,0.459035,33.090618,0.329963,1.023186,-2.571429
999995,2025-10-04,Saturday,4,40,10,4,P00200,Brand_E Tea Product 200,Beverages,Tea,...,5.236960,383.428571,118.571429,0,0.099602,0.461987,32.931581,0.325365,0.978134,-5.357143
999996,2025-10-05,Sunday,5,40,10,4,P00200,Brand_E Tea Product 200,Beverages,Tea,...,4.245902,732.000000,-288.000000,1,0.168919,0.498671,37.444244,0.353010,1.036729,-1.500000
999997,2025-10-06,Monday,6,41,10,4,P00200,Brand_E Tea Product 200,Beverages,Tea,...,1.804533,302.571429,-120.571429,1,0.549451,0.469279,38.009325,0.356417,0.974151,-5.785714
999998,2025-10-07,Tuesday,7,41,10,4,P00200,Brand_E Tea Product 200,Beverages,Tea,...,2.260417,109.714286,138.285714,0,0.806452,0.361483,37.306276,0.344517,1.042581,1.428571

In [192]:
nan_cols = [
    col for col in df.columns
    if df[col].isna().any()
]

print(nan_cols)

['sales_lag_1', 'sales_lag_3', 'sales_lag_7', 'sales_lag_14', 'sales_lag_30', 'rolling_mean_7', 'rolling_mean_14', 'rolling_mean_30', 'rolling_std_7', 'rolling_std_30', 'demand_change_1', 'demand_change_7', 'demand_ratio_7', 'growth_rate_7', 'price_lag_1', 'price_change_1', 'price_change_pct_1', 'inventory_coverage_days', 'lead_time_demand', 'inventory_gap', 'demand_cv_7', 'rolling_std_14', 'demand_cv_14', 'recent_vs_longterm_demand', 'demand_momentum_7']

In [193]:
history_features = [
    "sales_lag_30",
    "rolling_mean_30",
    "rolling_std_30",
    "demand_cv_14",
    "recent_vs_longterm_demand"
]

In [194]:
df = (
    df.groupby(["product_id", "store_id"], group_keys=False)
      .apply(lambda x: x.iloc[30:])
      .reset_index(drop=True)
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\12990052.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["product_id", "store_id"], group_keys=False)
C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\12990052.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.iloc[30:])

In [195]:
df = (
    df.sort_values(["product_id", "store_id", "date"])
      .groupby(["product_id", "store_id"], group_keys=False)
      .nth(slice(30, None))
      .reset_index()
)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\3387000421.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(["product_id", "store_id"], group_keys=False)

In [196]:
df["history_row_number"] = (
    df.groupby(["product_id", "store_id"])
      .cumcount()
)

df = df[
    df["history_row_number"] >= 30
].copy()

df.drop(columns=["history_row_number"], inplace=True)

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\2141911413.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["product_id", "store_id"])

In [197]:

remaining_nan = df.isna().sum()

print(
    remaining_nan[remaining_nan > 0]
)

Series([], dtype: int64)

In [198]:
numeric_cols = df.select_dtypes(include=np.number).columns

print(
    np.isinf(df[numeric_cols]).sum()
    .sum()
)

0

In [199]:
print("Shape:", df.shape)

print("\nRemaining NaN:")
print(df.isna().sum()[df.isna().sum() > 0])

print("\nInfinity count:")
print(np.isinf(
    df.select_dtypes(include=np.number)
).sum().sum())

Shape: (90000, 73)

Remaining NaN:
Series([], dtype: int64)

Infinity count:
0

In [200]:
print("Rows:", len(df))

print(
    df.groupby(["product_id", "store_id"])
      .size()
      .describe()
)

Rows: 90000
count    10000.0
mean         9.0
std          0.0
min          9.0
25%          9.0
50%          9.0
75%          9.0
max          9.0
dtype: float64

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\2428401266.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["product_id", "store_id"])

In [201]:
print("Unique products:", df["product_id"].nunique())
print("Unique stores:", df["store_id"].nunique())
print("Unique product-store pairs:",
      df[["product_id", "store_id"]].drop_duplicates().shape[0])

Unique products: 200
Unique stores: 50
Unique product-store pairs: 10000

In [202]:
print(df.groupby(["product_id", "store_id"])["date"].agg(["min", "max", "count"]).head(10))

                           min        max  count
product_id store_id
P00001     S0001    2025-09-29 2025-10-07      9
           S0002    2025-09-29 2025-10-07      9
           S0003    2025-09-29 2025-10-07      9
           S0004    2025-09-29 2025-10-07      9
           S0005    2025-09-29 2025-10-07      9
           S0006    2025-09-29 2025-10-07      9
           S0007    2025-09-29 2025-10-07      9
           S0008    2025-09-29 2025-10-07      9
           S0009    2025-09-29 2025-10-07      9
           S0010    2025-09-29 2025-10-07      9

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\1011808272.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(["product_id", "store_id"])["date"].agg(["min", "max", "count"]).head(10))

In [203]:
print(df.groupby(["product_id", "store_id"]).size().value_counts())

9    10000
Name: count, dtype: int64

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\347669449.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(["product_id", "store_id"]).size().value_counts())

In [204]:
print(df["date"].min())
print(df["date"].max())

2025-09-29 00:00:00
2025-10-07 00:00:00

In [205]:
print(df.groupby(["product_id", "store_id"]).size().value_counts())

print("Date range:", df["date"].min(), "to", df["date"].max())

9    10000
Name: count, dtype: int64
Date range: 2025-09-29 00:00:00 to 2025-10-07 00:00:00

C:\Users\Shivam shrivastav\AppData\Local\Temp\ipykernel_4248\2294268441.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(["product_id", "store_id"]).size().value_counts())

In [206]:
df = pd.read_csv("demandpulse_ai_clean.csv")

df["date"] = pd.to_datetime(df["date"])

df = df.sort_values(
    ["product_id", "store_id", "date"]
).reset_index(drop=True)

print("Shape:", df.shape)
print("Date range:", df["date"].min(), "to", df["date"].max())

Shape: (1000000, 35)
Date range: 2025-07-01 00:00:00 to 2025-10-08 00:00:00

In [207]:
print(
    df.groupby(["product_id", "store_id"])
      .size()
      .value_counts()
)

100    10000
Name: count, dtype: int64

In [208]:
df["future_demand"] = (
    df.groupby(["product_id", "store_id"])["quantity_sold"]
      .shift(-1)
)

In [209]:
group_cols = ["product_id", "store_id"]

df["future_demand"] = (
    df.groupby(group_cols)["quantity_sold"]
      .shift(-1)
)

In [210]:
print("Target NaN:", df["future_demand"].isna().sum())

Target NaN: 10000

In [211]:
for lag in [1, 3, 7, 14, 30]:
    df[f"sales_lag_{lag}"] = (
        df.groupby(group_cols)["quantity_sold"]
          .shift(lag)
    )

In [212]:
lag_cols = [
    "sales_lag_1",
    "sales_lag_3",
    "sales_lag_7",
    "sales_lag_14",
    "sales_lag_30"
]

print(df[lag_cols].isna().sum())

sales_lag_1      10000
sales_lag_3      30000
sales_lag_7      70000
sales_lag_14    140000
sales_lag_30    300000
dtype: int64

In [213]:
print("Shape:", df.shape)

Shape: (1000000, 41)

In [214]:
sample_series = df[
    (df["product_id"] == "P00001") &
    (df["store_id"] == "S0001")
][[
    "date",
    "quantity_sold",
    "future_demand",
    "sales_lag_1",
    "sales_lag_7",
    "sales_lag_30"
]]

print(sample_series.head(35))

         date  quantity_sold  future_demand  sales_lag_1  sales_lag_7  \
0  2025-07-01             71           97.0          NaN          NaN
1  2025-07-02             97          125.0         71.0          NaN
2  2025-07-03            125           64.0         97.0          NaN
3  2025-07-04             64          134.0        125.0          NaN
4  2025-07-05            134          102.0         64.0          NaN
5  2025-07-06            102           87.0        134.0          NaN
6  2025-07-07             87           98.0        102.0          NaN
7  2025-07-08             98           58.0         87.0         71.0
8  2025-07-09             58          102.0         98.0         97.0
9  2025-07-10            102           96.0         58.0        125.0
10 2025-07-11             96          118.0        102.0         64.0
11 2025-07-12            118           88.0         96.0        134.0
12 2025-07-13             88           68.0        118.0        102.0
13 2025-07-14             68           79.0         88.0         87.0
14 2025-07-15             79           76.0         68.0         98.0
15 2025-07-16             76          105.0         79.0         58.0
16 2025-07-17            105           66.0         76.0        102.0
17 2025-07-18             66          120.0        105.0         96.0
18 2025-07-19            120          130.0         66.0        118.0
19 2025-07-20            130           83.0        120.0         88.0
20 2025-07-21             83           93.0        130.0         68.0
21 2025-07-22             93           92.0         83.0         79.0
22 2025-07-23             92          103.0         93.0         76.0
23 2025-07-24            103           60.0         92.0        105.0
24 2025-07-25             60          110.0        103.0         66.0
25 2025-07-26            110           51.0         60.0        120.0
26 2025-07-27             51           66.0        110.0        130.0
27 2025-07-28             66           75.0         51.0         83.0
28 2025-07-29             75          103.0         66.0         93.0
29 2025-07-30            103           78.0         75.0         92.0
30 2025-07-31             78           78.0        103.0        103.0
31 2025-08-01             78           75.0         78.0         60.0
32 2025-08-02             75           80.0         78.0        110.0
33 2025-08-03             80           62.0         75.0         51.0
34 2025-08-04             62           97.0         80.0         66.0

    sales_lag_30
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6            NaN
7            NaN
8            NaN
9            NaN
10           NaN
11           NaN
12           NaN
13           NaN
14           NaN
15           NaN
16           NaN
17           NaN
18           NaN
19           NaN
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
25           NaN
26           NaN
27           NaN
28           NaN
29           NaN
30          71.0
31          97.0
32         125.0
33          64.0
34         134.0

In [215]:
group_cols = ["product_id", "store_id"]

# 7-day rolling
df["rolling_mean_7"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(7).mean())
)

# 14-day rolling
df["rolling_mean_14"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(14).mean())
)

# 30-day rolling
df["rolling_mean_30"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(30).mean())
)

# 7-day volatility
df["rolling_std_7"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(7).std())
)

# 30-day volatility
df["rolling_std_30"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(30).std())
)

# 14-day volatility
df["rolling_std_14"] = (
    df.groupby(group_cols)["quantity_sold"]
      .transform(lambda x: x.shift(1).rolling(14).std())
)

In [216]:
print("Shape:", df.shape)

Shape: (1000000, 47)

In [217]:
rolling_cols = [
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_30",
    "rolling_std_7",
    "rolling_std_14",
    "rolling_std_30"
]

print(df[rolling_cols].isna().sum())

rolling_mean_7      70000
rolling_mean_14    140000
rolling_mean_30    300000
rolling_std_7       70000
rolling_std_14     140000
rolling_std_30     300000
dtype: int64

In [218]:
print("Rows:", len(df))

Rows: 1000000

In [219]:
group_cols = ["product_id", "store_id"]

df["demand_change_1"] = (
    df.groupby(group_cols)["quantity_sold"]
      .diff(1)
)

In [220]:
df["demand_change_7"] = (
    df.groupby(group_cols)["quantity_sold"]
      .diff(7)
)

In [221]:
df["growth_rate_7"] = (
    df["quantity_sold"] /
    df.groupby(group_cols)["quantity_sold"].shift(7)
    - 1
)

In [222]:
df["demand_ratio_7"] = (
    df["quantity_sold"] /
    df["rolling_mean_7"]
)

In [223]:
df["demand_cv_7"] = (
    df["rolling_std_7"] /
    df["rolling_mean_7"]
)

In [224]:
df["demand_cv_14"] = (
    df["rolling_std_14"] /
    df["rolling_mean_14"]
)

In [225]:
df["recent_vs_longterm_demand"] = (
    df["rolling_mean_7"] /
    df["rolling_mean_30"]
)

In [226]:
df["demand_momentum_7"] = (
    df["rolling_mean_7"] -
    df["rolling_mean_14"]
)

In [227]:
print("Shape:", df.shape)

Shape: (1000000, 55)

In [228]:
trend_cols = [
    "demand_change_1",
    "demand_change_7",
    "growth_rate_7",
    "demand_ratio_7",
    "demand_cv_7",
    "demand_cv_14",
    "recent_vs_longterm_demand",
    "demand_momentum_7"
]

print(df[trend_cols].head(20))

    demand_change_1  demand_change_7  growth_rate_7  demand_ratio_7  \
0               NaN              NaN            NaN             NaN
1              26.0              NaN            NaN             NaN
2              28.0              NaN            NaN             NaN
3             -61.0              NaN            NaN             NaN
4              70.0              NaN            NaN             NaN
5             -32.0              NaN            NaN             NaN
6             -15.0              NaN            NaN             NaN
7              11.0             27.0       0.380282        1.008824
8             -40.0            -39.0      -0.402062        0.574257
9              44.0            -23.0      -0.184000        1.068862
10             -6.0             32.0       0.500000        1.041860
11             22.0            -16.0      -0.119403        1.220089
12            -30.0            -14.0      -0.137255        0.931921
13            -20.0            -19.0      -0.218391        0.735703
14             11.0            -19.0      -0.193878        0.880573
15             -3.0             18.0       0.310345        0.873563
16             29.0              3.0       0.029412        1.172249
17            -39.0            -30.0      -0.312500        0.733333
18             54.0              2.0       0.016949        1.400000
19             10.0             42.0       0.477273        1.511628

    demand_cv_7  demand_cv_14  recent_vs_longterm_demand  demand_momentum_7
0           NaN           NaN                        NaN                NaN
1           NaN           NaN                        NaN                NaN
2           NaN           NaN                        NaN                NaN
3           NaN           NaN                        NaN                NaN
4           NaN           NaN                        NaN                NaN
5           NaN           NaN                        NaN                NaN
6           NaN           NaN                        NaN                NaN
7      0.267213           NaN                        NaN                NaN
8      0.230646           NaN                        NaN                NaN
9      0.298598           NaN                        NaN                NaN
10     0.278982           NaN                        NaN                NaN
11     0.232794           NaN                        NaN                NaN
12     0.196592           NaN                        NaN                NaN
13     0.198698           NaN                        NaN                NaN
14     0.229314      0.244353                        NaN          -3.714286
15     0.236216      0.237440                        NaN          -7.000000
16     0.191629      0.246515                        NaN          -2.928571
17     0.195105      0.232549                        NaN          -1.071429
18     0.226497      0.230094                        NaN          -5.500000
19     0.232267      0.210999                        NaN          -4.214286

In [229]:
print(
    np.isinf(
        df[trend_cols].select_dtypes(include=np.number)
    ).sum().sum()
)

0

In [230]:
print(df[trend_cols].isna().sum())

demand_change_1               10000
demand_change_7               70000
growth_rate_7                 70000
demand_ratio_7                70000
demand_cv_7                   70000
demand_cv_14                 140000
recent_vs_longterm_demand    300000
demand_momentum_7            140000
dtype: int64

In [231]:
## Calendar Features

In [232]:
import numpy as np

# Day of week → numeric
day_map = {
    "Monday": 0,
    "Tuesday": 1,
    "Wednesday": 2,
    "Thursday": 3,
    "Friday": 4,
    "Saturday": 5,
    "Sunday": 6
}

df["day_of_week_num"] = (
    df["day_of_week"]
    .astype(str)
    .map(day_map)
    .astype("int8")
)

# Month start/end
df["is_month_start"] = (
    df["date"].dt.is_month_start
).astype("int8")

df["is_month_end"] = (
    df["date"].dt.is_month_end
).astype("int8")

# Week start/end
df["is_week_start"] = (
    df["date"].dt.dayofweek == 0
).astype("int8")

df["is_week_end"] = (
    df["date"].dt.dayofweek == 6
).astype("int8")

# Cyclical weekly features
df["day_of_week_sin"] = np.sin(
    2 * np.pi * df["day_of_week_num"] / 7
)

df["day_of_week_cos"] = np.cos(
    2 * np.pi * df["day_of_week_num"] / 7
)

# Cyclical monthly features
df["month_sin"] = np.sin(
    2 * np.pi * (df["month"] - 1) / 12
)

df["month_cos"] = np.cos(
    2 * np.pi * (df["month"] - 1) / 12
)

In [233]:
## Price & Promotion

In [234]:
group_cols = ["product_id", "store_id"]

# Effective price after discount
df["effective_price"] = (
    df["average_selling_price"] *
    (1 - df["discount_percentage"] / 100)
)

# Previous day's price
df["price_lag_1"] = (
    df.groupby(group_cols)["average_selling_price"]
      .shift(1)
)

# Absolute price change
df["price_change_1"] = (
    df["average_selling_price"] -
    df["price_lag_1"]
)

# Percentage price change
df["price_change_pct_1"] = (
    (df["average_selling_price"] /
     df["price_lag_1"]) - 1
)

In [235]:
## Inventory & Supply

In [236]:
# Inventory coverage in days
df["inventory_coverage_days"] = (
    df["inventory_level"] /
    df["rolling_mean_7"]
)

# Expected demand during supplier lead time
df["lead_time_demand"] = (
    df["rolling_mean_7"] *
    df["lead_time_days"]
)

# Inventory surplus/shortage
df["inventory_gap"] = (
    df["inventory_level"] -
    df["lead_time_demand"]
)

# Potential stockout risk
df["potential_stockout_risk"] = (
    df["inventory_level"] <
    df["lead_time_demand"]
).astype("int8")

# MOQ relative to inventory
df["moq_inventory_ratio"] = (
    df["minimum_order_quantity"] /
    df["inventory_level"].replace(0, np.nan)
)

In [237]:
print("Shape:", df.shape)

Shape: (1000000, 73)

In [238]:
new_features = [
    "day_of_week_num",
    "is_month_start",
    "is_month_end",
    "is_week_start",
    "is_week_end",
    "day_of_week_sin",
    "day_of_week_cos",
    "month_sin",
    "month_cos",
    "effective_price",
    "price_lag_1",
    "price_change_1",
    "price_change_pct_1",
    "inventory_coverage_days",
    "lead_time_demand",
    "inventory_gap",
    "potential_stockout_risk",
    "moq_inventory_ratio"
]

print(df[new_features].head())

   day_of_week_num  is_month_start  is_month_end  is_week_start  is_week_end  \
0                1               1             0              0            0
1                2               0             0              0            0
2                3               0             0              0            0
3                4               0             0              0            0
4                5               0             0              0            0

   day_of_week_sin  day_of_week_cos     month_sin  month_cos  effective_price  \
0         0.781831         0.623490  1.224647e-16       -1.0       615.640584
1         0.974928        -0.222521  1.224647e-16       -1.0       743.990000
2         0.433884        -0.900969  1.224647e-16       -1.0       713.600000
3        -0.433884        -0.900969  1.224647e-16       -1.0       733.950000
4        -0.974928        -0.222521  1.224647e-16       -1.0       391.747488

   price_lag_1  price_change_1  price_change_pct_1  inventory_coverage_days  \
0          NaN             NaN                 NaN                      NaN
1       658.58           85.41            0.129688                      NaN
2       743.99          -30.39           -0.040847                      NaN
3       713.60           20.35            0.028517                      NaN
4       733.95         -200.67           -0.273411                      NaN

   lead_time_demand  inventory_gap  potential_stockout_risk  \
0               NaN            NaN                        0
1               NaN            NaN                        0
2               NaN            NaN                        0
3               NaN            NaN                        0
4               NaN            NaN                        0

   moq_inventory_ratio
0             0.165563
1             0.534759
2             0.178571
3             0.078740
4             0.077399

In [239]:
print("Rows:", len(df))

print(
    "Duplicate product-store-date:",
    df.duplicated(
        ["product_id", "store_id", "date"]
    ).sum()
)

Rows: 1000000
Duplicate product-store-date: 0

In [240]:
numeric_cols = df.select_dtypes(include=np.number).columns

df[numeric_cols] = df[numeric_cols].replace([np.inf, -np.inf],np.nan)

In [241]:
df = df.dropna(subset=["future_demand"]).copy()

print("After target removal:", df.shape)

After target removal: (990000, 73)

In [242]:
## 30-day history requirement

df["history_row_number"] = (
    df.groupby(["product_id", "store_id"])
      .cumcount()
)

df = df[
    df["history_row_number"] >= 30
].copy()

df.drop(columns=["history_row_number"], inplace=True)

In [243]:
print("Final modeling dataset shape:", df.shape)

Final modeling dataset shape: (690000, 73)

In [244]:
## Final NaN check

remaining_nan = df.isna().sum()

print(remaining_nan[remaining_nan > 0])

Series([], dtype: int64)

In [245]:
# Final Infinity check

numeric_cols = df.select_dtypes(include=np.number).columns

print("Infinity count:",np.isinf(df[numeric_cols]).sum().sum())

Infinity count: 0

In [246]:
## Series validation

series_counts = (df.groupby(["product_id", "store_id"]).size())

print(series_counts.value_counts())

69    10000
Name: count, dtype: int64

In [247]:
## Target Define

In [248]:
target = "future_demand"

In [249]:
print("Target:", target)
print("Target dtype:", df[target].dtype)
print("Target shape:", df[target].shape)

Target: future_demand
Target dtype: float64
Target shape: (690000,)

In [250]:
## Columns Exclude

exclude_cols = ["future_demand","date"]

In [251]:
X = df.drop(columns=exclude_cols)
y = df["future_demand"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (690000, 71)
y shape: (690000,)

In [252]:
# Leakage Audit

In [253]:
print("Target in X:", target in X.columns)

Target in X: False

In [254]:
print("Date in X:", "date" in X.columns)

Date in X: False

In [255]:
## Feature Categories

In [256]:
demand_features = [
    "sales_lag_1",
    "sales_lag_3",
    "sales_lag_7",
    "sales_lag_14",
    "sales_lag_30",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_30",
    "rolling_std_7",
    "rolling_std_14",
    "rolling_std_30",
    "demand_change_1",
    "demand_change_7",
    "growth_rate_7",
    "demand_ratio_7",
    "demand_cv_7",
    "demand_cv_14",
    "recent_vs_longterm_demand",
    "demand_momentum_7"
]

In [257]:
calendar_features = [
    "day_of_week",
    "day_of_week_num",
    "day_of_month",
    "week_of_year",
    "month",
    "quarter",
    "is_weekend",
    "is_holiday",
    "season",
    "special_event",
    "is_month_start",
    "is_month_end",
    "is_week_start",
    "is_week_end",
    "day_of_week_sin",
    "day_of_week_cos",
    "month_sin",
    "month_cos"
]

In [258]:
price_promotion_features = [
    "average_selling_price",
    "discount_percentage",
    "is_promoted",
    "promotion_type",
    "effective_price",
    "price_lag_1",
    "price_change_1",
    "price_change_pct_1"
]

In [259]:
inventory_features = [
    "inventory_level",
    "lead_time_days",
    "stockout_flag",
    "minimum_order_quantity",
    "inventory_coverage_days",
    "lead_time_demand",
    "inventory_gap",
    "potential_stockout_risk",
    "moq_inventory_ratio"
]

In [260]:
print("Total columns:", len(df.columns))
print("Feature columns:", len(X.columns))
print("Target:", target)

print("\nFeature list:")
for i, col in enumerate(X.columns, start=1):
    print(i, col)

Total columns: 73
Feature columns: 71
Target: future_demand

Feature list:
1 day_of_week
2 day_of_month
3 week_of_year
4 month
5 quarter
6 year
7 product_id
8 product_name
9 category
10 subcategory
11 brand
12 unit_of_measure
13 store_id
14 store_type
15 store_location
16 city
17 region
18 quantity_sold
19 sales_amount
20 number_of_transactions
21 average_selling_price
22 promotion_type
23 discount_percentage
24 is_promoted
25 is_weekend
26 is_holiday
27 holiday_name
28 season
29 special_event
30 inventory_level
31 lead_time_days
32 stockout_flag
33 supplier_id
34 minimum_order_quantity
35 sales_lag_1
36 sales_lag_3
37 sales_lag_7
38 sales_lag_14
39 sales_lag_30
40 rolling_mean_7
41 rolling_mean_14
42 rolling_mean_30
43 rolling_std_7
44 rolling_std_30
45 rolling_std_14
46 demand_change_1
47 demand_change_7
48 growth_rate_7
49 demand_ratio_7
50 demand_cv_7
51 demand_cv_14
52 recent_vs_longterm_demand
53 demand_momentum_7
54 day_of_week_num
55 is_month_start
56 is_month_end
57 is_week_start
58 is_week_end
59 day_of_week_sin
60 day_of_week_cos
61 month_sin
62 month_cos
63 effective_price
64 price_lag_1
65 price_change_1
66 price_change_pct_1
67 inventory_coverage_days
68 lead_time_demand
69 inventory_gap
70 potential_stockout_risk
71 moq_inventory_ratio

In [261]:
## Data Types

In [262]:
print(X.dtypes.value_counts())

float64    34
object     17
int64      14
int8        6
Name: count, dtype: int64

In [263]:
## Final X/y Check

In [264]:
print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nX missing values:")
print(X.isna().sum().sum())

print("\ny missing values:")
print(y.isna().sum())

X shape: (690000, 71)
y shape: (690000,)

X missing values:
0

y missing values:
0

In [265]:
## Date-Based Train/Test Split

In [266]:
test_days = 14

max_date = df["date"].max()
test_start_date = max_date - pd.Timedelta(days=test_days - 1)

train_df = df[
    df["date"] < test_start_date
].copy()

test_df = df[
    df["date"] >= test_start_date
].copy()

print("Train shape:", train_df.shape)
print("Test shape :", test_df.shape)

print("\nTrain dates:")
print(train_df["date"].min(), "→", train_df["date"].max())

print("\nTest dates:")
print(test_df["date"].min(), "→", test_df["date"].max())

Train shape: (550000, 73)
Test shape : (140000, 73)

Train dates:
2025-07-31 00:00:00 → 2025-09-23 00:00:00

Test dates:
2025-09-24 00:00:00 → 2025-10-07 00:00:00

In [267]:
## X and y Separate

In [268]:
target = "future_demand"

exclude_cols = [
    "future_demand",
    "date"
]

X_train = train_df.drop(columns=exclude_cols)
y_train = train_df[target]

X_test = test_df.drop(columns=exclude_cols)
y_test = test_df[target]

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_test :", X_test.shape)
print("y_test :", y_test.shape)

X_train: (550000, 71)
y_train: (550000,)
X_test : (140000, 71)
y_test : (140000,)

In [269]:
## Feature Selection Categories

In [270]:
id_features = [
    "product_id",
    "product_name",
    "store_id",
    "supplier_id"
]

In [271]:
redundant_candidates = [
    "day_of_week_num",
    "is_weekend",
    "is_week_start",
    "is_week_end"
]

In [272]:
## Constant Features

In [273]:
constant_features = ["quarter", "year", "season"]

X_train = X_train.drop(
    columns=constant_features,
    errors="ignore"
)

X_test = X_test.drop(
    columns=constant_features,
    errors="ignore"
)

print("Constant features removed safely.")

Constant features removed safely.

In [274]:
print("quarter:", "quarter" in X_train.columns)
print("year:", "year" in X_train.columns)
print("season:", "season" in X_train.columns)

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

quarter: False
year: False
season: False
X_train shape: (550000, 68)
X_test shape : (140000, 68)

In [275]:
## Duplicate Features

In [280]:
duplicate_features = []

cols = X_train.columns

for i in range(len(cols)):
    for j in range(i + 1, len(cols)):
        if X_train[cols[i]].equals(X_train[cols[j]]):
            duplicate_features.append(
                (cols[i], cols[j])
            )

print("Duplicate feature pairs:")
print(duplicate_features)

Duplicate feature pairs:
[]

In [281]:
## Numeric Correlation

In [282]:
numeric_features = X_train.select_dtypes(
    include=np.number
).columns.tolist()

print("Number of numeric features:", len(numeric_features))
print(numeric_features)

Number of numeric features: 52
['day_of_month', 'week_of_year', 'month', 'quantity_sold', 'sales_amount', 'number_of_transactions', 'average_selling_price', 'discount_percentage', 'is_promoted', 'is_weekend', 'is_holiday', 'inventory_level', 'lead_time_days', 'stockout_flag', 'minimum_order_quantity', 'sales_lag_1', 'sales_lag_3', 'sales_lag_7', 'sales_lag_14', 'sales_lag_30', 'rolling_mean_7', 'rolling_mean_14', 'rolling_mean_30', 'rolling_std_7', 'rolling_std_30', 'rolling_std_14', 'demand_change_1', 'demand_change_7', 'growth_rate_7', 'demand_ratio_7', 'demand_cv_7', 'demand_cv_14', 'recent_vs_longterm_demand', 'demand_momentum_7', 'day_of_week_num', 'is_month_start', 'is_month_end', 'is_week_start', 'is_week_end', 'day_of_week_sin', 'day_of_week_cos', 'month_sin', 'month_cos', 'effective_price', 'price_lag_1', 'price_change_1', 'price_change_pct_1', 'inventory_coverage_days', 'lead_time_demand', 'inventory_gap', 'potential_stockout_risk', 'moq_inventory_ratio']

In [283]:
print("Train shape:", train_df.shape)
print("Test shape :", test_df.shape)

print("\nConstant features:")
print(constant_features)

print("\nDuplicate features:")
print(duplicate_features)

print("\nTop correlations:")
print(corr_with_target.head(15))

Train shape: (550000, 73)
Test shape : (140000, 73)

Constant features:
['quarter', 'year', 'season']

Duplicate features:
[]

Top correlations:

NameError: name 'corr_with_target' is not defined

In [ ]:
from sklearn.feature_selection import mutual_info_regression

mi_scores = mutual_info_regression(
    mi_sample,
    mi_target,
    random_state=42
)

mi_df = pd.DataFrame({
    "feature": numeric_features,
    "mi_score": mi_scores
}).sort_values(
    "mi_score",
    ascending=False
)

In [ ]:
print(mi_df.head(20).to_string(index=False))

In [ ]:
## Feature Correlation Matrix

In [ ]:
top_mi_features = mi_df.head(20)["feature"].tolist()

feature_corr = X_train[top_mi_features].corr()

print(feature_corr.round(2))

In [ ]:
## specifically highly correlated pairs

In [ ]:
high_corr_pairs = []

for i in range(len(top_mi_features)):
    for j in range(i + 1, len(top_mi_features)):
        corr_value = feature_corr.iloc[i, j]

        if abs(corr_value) >= 0.90:
            high_corr_pairs.append(
                (
                    top_mi_features[i],
                    top_mi_features[j],
                    round(corr_value, 3)
                )
            )

print("Highly correlated pairs:")
for pair in high_corr_pairs:
    print(pair)

In [ ]:
## Feature Selection Decision

In [ ]:
# Compare important correlated features with target
comparison_features = [
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_30",
    "rolling_std_14",
    "rolling_std_30",
    "quantity_sold",
    "number_of_transactions"
]

comparison = pd.DataFrame({
    "feature": comparison_features,
    "correlation_with_target": [
        X_train[f].corr(y_train) for f in comparison_features
    ],
    "mutual_information": [
        mi_df.loc[mi_df["feature"] == f, "mi_score"].iloc[0]
        for f in comparison_features
    ]
})

comparison = comparison.sort_values(
    "mutual_information",
    ascending=False
)

print(comparison.to_string(index=False))

In [ ]:
features_to_remove = [
    "rolling_std_14",
    "number_of_transactions"
]

X_train = X_train.drop(columns=features_to_remove, errors="ignore")
X_test = X_test.drop(columns=features_to_remove, errors="ignore")

In [ ]:
id_features = [
    "product_id",
    "product_name",
    "store_id",
    "supplier_id"
]

print("ID / Identifier Features:")
for feature in id_features:
    print(
        feature,
        "→",
        X_train[feature].nunique(),
        "unique values"
    )

In [ ]:
features_to_remove = [
    "rolling_std_14",
    "number_of_transactions",
    "product_name"
]

X_train = X_train.drop(columns=features_to_remove, errors="ignore")
X_test = X_test.drop(columns=features_to_remove, errors="ignore")

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)

In [ ]:
print("Remaining categorical features:")
print(X_train.select_dtypes(include=["object", "category"]).columns.tolist())

print("\nRemaining numeric features:")
print(X_train.select_dtypes(include=np.number).columns.tolist())

In [ ]:
## Feature Importance using a Baseline Model

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Numeric features only
numeric_features = X_train.select_dtypes(include=np.number).columns.tolist()

# Sample training data for faster feature importance calculation
sample_size = min(100000, len(X_train))

X_sample = X_train[numeric_features].sample(
    n=sample_size,
    random_state=42
)

y_sample = y_train.loc[X_sample.index]

print("Sample shape:", X_sample.shape)

rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=12,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_sample, y_sample)

rf_importance = pd.DataFrame({
    "feature": numeric_features,
    "importance": rf.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

print(rf_importance.head(25).to_string(index=False))

In [ ]:
## Final Selected Features Create

In [ ]:
selected_features = [
    # Demand history
    "quantity_sold",
    "sales_lag_1",
    "sales_lag_3",
    "sales_lag_7",
    "sales_lag_14",
    "sales_lag_30",
    "rolling_mean_7",
    "rolling_mean_14",
    "rolling_mean_30",
    "rolling_std_7",
    "rolling_std_30",
    "demand_change_1",
    "demand_change_7",
    "growth_rate_7",
    "demand_ratio_7",
    "demand_cv_7",
    "demand_cv_14",
    "recent_vs_longterm_demand",
    "demand_momentum_7",

    # Calendar
    "day_of_month",
    "week_of_year",
    "month",
    "day_of_week_num",
    "day_of_week_sin",
    "day_of_week_cos",
    "month_sin",
    "month_cos",
    "is_weekend",
    "is_holiday",
    "is_month_start",
    "is_month_end",
    "is_week_start",
    "is_week_end",

    # Price / Promotion
    "average_selling_price",
    "discount_percentage",
    "is_promoted",
    "effective_price",
    "price_lag_1",
    "price_change_1",
    "price_change_pct_1",

    # Inventory / Supply
    "inventory_level",
    "lead_time_days",
    "stockout_flag",
    "minimum_order_quantity",
    "inventory_coverage_days",
    "lead_time_demand",
    "inventory_gap",
    "potential_stockout_risk",
    "moq_inventory_ratio",

    # Product / Store / Supply-chain categorical
    "product_id",
    "category",
    "subcategory",
    "brand",
    "unit_of_measure",
    "store_id",
    "store_type",
    "store_location",
    "city",
    "region",
    "promotion_type",
    "holiday_name",
    "special_event",
    "supplier_id",
    "day_of_week"
]

print("Total selected features:", len(selected_features))

In [ ]:
missing_features = [
    f for f in selected_features
    if f not in X_train.columns
]

print("Missing features:", missing_features)
print("Selected features available:", len(selected_features) - len(missing_features))

In [ ]:
X_train_selected = X_train[selected_features].copy()
X_test_selected = X_test[selected_features].copy()

print("X_train_selected shape:", X_train_selected.shape)
print("X_test_selected shape :", X_test_selected.shape)

print("\nTarget shapes:")
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

In [ ]:
## Final Data Quality Check

In [ ]:
# Missing values
print("Missing values in X_train:",
      X_train_selected.isna().sum().sum())

print("Missing values in X_test:",
      X_test_selected.isna().sum().sum())

# Infinite values — numeric columns only
train_numeric = X_train_selected.select_dtypes(include=np.number)
test_numeric = X_test_selected.select_dtypes(include=np.number)

print("\nInfinite values in X_train:",
      np.isinf(train_numeric).sum().sum())

print("Infinite values in X_test:",
      np.isinf(test_numeric).sum().sum())

In [ ]:
## Check Target

In [ ]:
print("Target:", y_train.name)

print("\nTarget statistics:")
print(y_train.describe())

print("\nTarget missing values:")
print("Train:", y_train.isna().sum())
print("Test :", y_test.isna().sum())

In [ ]:
## Separate Numeric & Categorical Features

In [ ]:
# Identify categorical and numerical features

categorical_features = X_train_selected.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numeric_features = X_train_selected.select_dtypes(
    include=np.number
).columns.tolist()

print("Number of categorical features:", len(categorical_features))
print("Number of numerical features:", len(numeric_features))

print("\nCategorical features:")
print(categorical_features)

print("\nNumerical features:")
print(numeric_features)

In [ ]:
## Create Preprocessor

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Numerical pipeline
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

# Categorical pipeline
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=True
    ))
])

# Combined preprocessing
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

print("Preprocessor created successfully.")

In [ ]:
## Fit on Training Data

In [ ]:
# Fit preprocessing only on training data
preprocessor.fit(X_train_selected)

print("Preprocessor fitted successfully.")

In [ ]:
X_train_processed = preprocessor.transform(X_train_selected)
X_test_processed = preprocessor.transform(X_test_selected)

print("X_train_processed shape:", X_train_processed.shape)
print("X_test_processed shape :", X_test_processed.shape)

In [ ]:
print("Processed train shape:", X_train_processed.shape)
print("Processed test shape :", X_test_processed.shape)

print("\nTarget train shape:", y_train.shape)
print("Target test shape :", y_test.shape)

print("\nPreprocessing complete.")

In [ ]:
## Train Baseline

In [ ]:
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Baseline regression model
baseline_model = Ridge(alpha=1.0)

# Train
baseline_model.fit(X_train_processed, y_train)

print("Baseline model trained successfully.")

In [ ]:
## Predictions

In [ ]:
y_pred_baseline = baseline_model.predict(X_test_processed)

print("Predictions generated.")
print("Number of predictions:", len(y_pred_baseline))

In [ ]:
## Evaluation

In [ ]:
mae = mean_absolute_error(y_test, y_pred_baseline)
rmse = np.sqrt(mean_squared_error(y_test, y_pred_baseline))
r2 = r2_score(y_test, y_pred_baseline)

print("Baseline Model Performance")
print("-" * 35)
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R²   : {r2:.4f}")

In [ ]:
## Training Sample

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Use a manageable sample for model experimentation
rf_sample_size = min(150000, X_train_processed.shape[0])

sample_indices = np.random.RandomState(42).choice(
    X_train_processed.shape[0],
    size=rf_sample_size,
    replace=False
)

X_rf_sample = X_train_processed[sample_indices]
y_rf_sample = y_train.iloc[sample_indices]

print("Random Forest training sample:")
print("X:", X_rf_sample.shape)
print("y:", y_rf_sample.shape)

In [ ]:
## Train Random Forest

In [ ]:
rf_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=15,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rf_model.fit(X_rf_sample, y_rf_sample)

print("Random Forest trained successfully.")

In [ ]:
## Predict

In [ ]:
y_pred_rf = rf_model.predict(X_test_processed)

print("Random Forest predictions generated.")
print("Number of predictions:", len(y_pred_rf))

In [ ]:
## Evaluate

In [ ]:
rf_mae = mean_absolute_error(y_test, y_pred_rf)
rf_rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
rf_r2 = r2_score(y_test, y_pred_rf)

print("Random Forest Performance")
print("-" * 35)
print(f"MAE  : {rf_mae:.4f}")
print(f"RMSE : {rf_rmse:.4f}")
print(f"R²   : {rf_r2:.4f}")